import test from "node:test";import assert from "node:assert/strict";import{canTransition,transitionMission}from "../lib/engine.ts";import{evaluateMissionAction}from "../lib/policy.ts";import{assessOutcome}from "../lib/outcome-quality.ts";import{buildLearningLesson}from "../lib/learning-engine.ts";import{buildDecisionMatrix}from "../lib/decision-matrix.ts";import{buildAuditChain,verifyAuditChain}from "../lib/audit-chain.ts";
test("mission state machine",()=>{assert.equal(canTransition("AWAITING_APPROVAL","APPROVED"),true);assert.equal(canTransition("LEARNED","EXECUTING"),false);const m={id:"m",decisionId:"d",objective:"x",state:"AWAITING_APPROVAL" as const,kpi:"k",createdAt:"",updatedAt:"",executionCount:0};assert.equal(transitionMission(m,"APPROVED").state,"APPROVED")});
test("policy actor split",()=>{assert.equal(evaluateMissionAction("approve","AWAITING_APPROVAL").actor,"human");assert.equal(evaluateMissionAction("execute","APPROVED").actor,"system");assert.equal(evaluateMissionAction("execute","AWAITING_APPROVAL").allowed,false)});
test("outcome and learning",()=>{const a=assessOutcome({before:2.8,after:3.4,direction:"higher"});assert.equal(a.quality,"VERIFIED");assert.equal(buildLearningLesson(a,{missionObjective:"x",kpi:"conversion"}).lessonType,"POSITIVE_DELTA")});
test("decision matrix",()=>{const d={id:"d",diagnosis:"x",recommendation:"Proceed",confidence:.8,priority:"HIGH" as const,evidence:[],reasoningSource:"DETERMINISTIC_RULES" as const};assert.equal(buildDecisionMatrix(d).action,"PROCEED")});
test("audit detects tamper",async()=>{const c=await buildAuditChain({signals:[],decision:{},mission:{},trace:[]});assert.equal((await verifyAuditChain(c)).valid,true);c[0].hash="tampered";assert.equal((await verifyAuditChain(c)).valid,false)});
import{buildPredictiveDecision}from "../lib/predictive-decision.ts";
test("M9.6 predictive decision layer",()=>{const p=buildPredictiveDecision({signals:[{name:"conversion_rate",value:"4%",source:"test"},{name:"traffic",value:"+12%",source:"test"},{name:"qualified_leads",value:"+8%",source:"test"}],confidence:.8,recommendation:"Improve conversion",learningCount:3});assert.equal(p.version,"m9.6-predictive-v1");assert.ok(p.confidence>=0&&p.confidence<=1);assert.equal(p.scenarios.length,3);assert.ok(Math.abs(p.scenarios.reduce((a,s)=>a+s.probability,0)-1)<0.001);assert.ok(p.trigger.length>0);});

import{buildAdaptiveDecisionPolicy}from "../lib/adaptive-decision-policy.ts";
test("M9.7 adaptive decision policy",()=>{const p=buildAdaptiveDecisionPolicy({prediction:{version:"m9.6-predictive-v1",horizon:"7D",outcome:"UNCERTAIN",expectedImpactPct:null,confidence:.5,risk:"HIGH",leadingIndicators:[],failureModes:[],trigger:"t",invalidation:"i",scenarios:[],source:"DETERMINISTIC_PREDICTIVE",truthModel:"DERIVED"},history:[],learningCount:0});assert.equal(p.version,"m9.7-adaptive-v1");assert.equal(p.mode,"ABSTAIN");assert.ok(p.actionThreshold>=.8);assert.ok(p.confidenceThreshold>=.78);});
