import assert from "node:assert/strict";import test from "node:test";
import {authorizeRuntime,idempotencyKey,retryDecision,circuitState} from "../lib/universal-agent-os/runtime";
import {negotiate,makeEnvelope,compatible} from "../lib/universal-agent-os/interoperability";
import {shouldPromote,regression,confidence,canary} from "../lib/universal-agent-os/learning";
import {roi,optimizePortfolio,certificationRequired,capacityGap} from "../lib/universal-agent-os/economy";
test("M221-M225 runtime governance",()=>{const t={tenantId:"t",missionId:"m",taskId:"x",agentId:"a",input:{},risk:"HIGH" as const,attempt:1,correlationId:"c"};assert.equal(authorizeRuntime(t,{maxRetries:3,timeoutMs:1000,budget:10,maxRisk:"HIGH",killSwitch:false}).allowed,true);assert.equal(retryDecision(2,{maxRetries:3,timeoutMs:1,budget:1,maxRisk:"HIGH",killSwitch:false}),true);assert.equal(circuitState(3,3),"OPEN");assert.equal(idempotencyKey(t),"t:m:x:c")});
test("M226-M250 agent interoperability",()=>{const a={agentId:"a",tenantId:"t",version:"1.0.0",trusted:true,capabilities:["search","plan"]};const b={agentId:"b",tenantId:"t",version:"1.2.0",trusted:true,capabilities:["search","plan"]};assert.equal(negotiate(a,b,["search"]).accepted,true);assert.equal(makeEnvelope(a,b,"TASK",{}, "msg","corr").protocol,"A2A");assert.equal(compatible("1.2","1.9"),true)});
test("M251-M275 learning control",()=>{const base=[{sampleId:"1",skillId:"s",quality:.9,verified:true,latencyMs:10,cost:1}];const cand=[{sampleId:"2",skillId:"s",quality:.95,verified:true,latencyMs:10,cost:1},{sampleId:"3",skillId:"s",quality:.94,verified:true,latencyMs:10,cost:1}];assert.equal(regression(base,cand,.1),false);assert.equal(shouldPromote(cand,{minSamples:2,regressionDelta:.1,promotionQuality:.8,canaryRate:.1}),true);assert.ok(confidence(cand)>0);assert.equal(canary(10,{minSamples:1,regressionDelta:.1,promotionQuality:.8,canaryRate:.1}),1)});
test("M276-M300 skill economy",()=>{const x={skillId:"s",cost:2,latencyMs:10,successRate:.95,demand:10,capacity:20,trust:.9,certified:true};assert.equal(roi(x,6),2);assert.equal(certificationRequired(x),false);assert.equal(capacityGap(x),0);assert.equal(optimizePortfolio([x],10)[0].units,5)});
