import test from "node:test";
import assert from "node:assert/strict";
import { evaluatePolicyAwareRecoveryDecision } from "@/lib/m24-28-policy-aware-decision-engine";
import type { RecoveryDecisionResult } from "@/lib/recovery-decision-engine";
import type { RecoveryLearningPolicy } from "@/lib/m24-27-learning-policy-contract";
const base: RecoveryDecisionResult={tenantId:"tenant-a",recoveryKey:"recovery-1",commitId:"commit-1",payloadHash:"hash-1",decision:"RECONCILE",reasons:["state is valid"],checks:[],requiresApproval:true,evaluatedAt:"2026-10-04T00:00:00.000Z",source:"RECOVERY_STATE"};
const policy=(overrides:Partial<RecoveryLearningPolicy>={}):RecoveryLearningPolicy=>({tenantId:"tenant-a",recoveryKey:"recovery-1",action:"RESUME",sampleCount:4,successCount:4,partialCount:0,failedCount:0,unverifiedCount:0,netWeight:4,confidenceBps:10000,policyVersion:4,source:"PROMOTED_LEARNING",aggregatedAt:"2026-10-04T00:00:00.000Z",...overrides});
test("M24.28 promotes a safe policy-supported action",async()=>{const result=await evaluatePolicyAwareRecoveryDecision(base,[policy()]);assert.equal(result.decision,"RESUME");assert.equal(result.policyAdjusted,true);assert.equal(result.selectedPolicy?.action,"RESUME");assert.equal(result.requiresApproval,true);});
test("M24.28 rejects low-confidence policy",async()=>{const result=await evaluatePolicyAwareRecoveryDecision(base,[policy({confidenceBps:4999,netWeight:10})]);assert.equal(result.decision,"RECONCILE");assert.equal(result.selectedPolicy,null);});
test("M24.28 selects strongest eligible policy",async()=>{const result=await evaluatePolicyAwareRecoveryDecision(base,[policy({action:"REPLAY",netWeight:2,confidenceBps:9000}),policy({action:"RESUME",netWeight:3,confidenceBps:8000})]);assert.equal(result.decision,"RESUME");});
test("M24.28 never auto-executes",async()=>{const result=await evaluatePolicyAwareRecoveryDecision(base,[policy()]);assert.equal(result.requiresApproval,true);assert.notEqual(result.decision,"NO_ACTION");});
