import test from "node:test";
import assert from "node:assert/strict";
import { evaluateApprovalRequest, evaluatePolicyConfidenceEscalation } from "@/lib/recovery-approval-gate";

const decision={tenantId:"tenant-a",recoveryKey:"recovery-1",commitId:"commit-1",payloadHash:"hash-1",decision:"RESUME" as const,reasons:["policy"],checks:[{name:"POLICY" as const,passed:true,reason:"policy supports RESUME"}],requiresApproval:true,evaluatedAt:"2026-10-04T00:00:00.000Z",source:"RECOVERY_STATE + LEARNING_POLICY" as const,policySource:"LEARNING_POLICY" as const,selectedPolicy:{tenantId:"tenant-a",recoveryKey:"recovery-1",action:"RESUME" as const,sampleCount:5,successCount:5,partialCount:0,failedCount:0,unverifiedCount:0,netWeight:5,confidenceBps:10000,policyVersion:5,source:"PROMOTED_LEARNING" as const,aggregatedAt:"2026-10-04T00:00:00.000Z"},candidatePolicies:[],policyAdjusted:true};

test("M24.29 supported policy",()=>{const r=evaluateApprovalRequest({tenantId:"tenant-a",recoveryKey:"recovery-1",decision,action:"APPROVE",actorId:"human-1",actorKind:"human",idempotencyKey:"idem-1",policyWeight:{netWeight:5,confidenceBps:10000,sampleCount:5,policyVersion:5}});assert.equal(r.executionPermission,"GRANTED");assert.equal(r.approvalTier,"POLICY_SUPPORTED");});
test("M24.30 high confidence",()=>{const r=evaluatePolicyConfidenceEscalation({netWeight:5,confidenceBps:8000,sampleCount:5,policyVersion:5});assert.equal(r.level,"STANDARD_APPROVAL");});
test("M24.30 medium confidence",()=>{const r=evaluatePolicyConfidenceEscalation({netWeight:1,confidenceBps:5000,sampleCount:2,policyVersion:2});assert.equal(r.level,"ENHANCED_REVIEW");assert.equal(r.requiresEnhancedReview,true);});
test("M24.30 low confidence",()=>{const r=evaluatePolicyConfidenceEscalation({netWeight:1,confidenceBps:4999,sampleCount:1,policyVersion:1});assert.equal(r.level,"MANUAL_ESCALATION");assert.equal(r.requiresManualEscalation,true);});
test("M24.30 negative weight",()=>{const r=evaluatePolicyConfidenceEscalation({netWeight:-1,confidenceBps:10000,sampleCount:20,policyVersion:20});assert.equal(r.level,"MANUAL_ESCALATION");});
test("M24.30 no policy",()=>{const r=evaluatePolicyConfidenceEscalation(null);assert.equal(r.level,"MANUAL_ESCALATION");});
test("M24.30 human approval remains explicit",()=>{const r=evaluateApprovalRequest({tenantId:"tenant-a",recoveryKey:"recovery-1",decision,action:"APPROVE",actorId:"human-1",actorKind:"human",idempotencyKey:"idem-30",policyWeight:{netWeight:1,confidenceBps:4999,sampleCount:1,policyVersion:1}});assert.equal(r.executionPermission,"GRANTED");assert.equal(r.confidenceEscalation.level,"MANUAL_ESCALATION");});
test("M24.29 rejection denied",()=>{const r=evaluateApprovalRequest({tenantId:"tenant-a",recoveryKey:"recovery-1",decision,action:"REJECT",actorId:"human-1",actorKind:"human",idempotencyKey:"idem-3",policyWeight:{netWeight:5,confidenceBps:10000,sampleCount:5,policyVersion:5}});assert.equal(r.executionPermission,"DENIED");});
