"use client";
import {useState} from "react";
import {ArrowRight,BrainCircuit,CheckCircle2,ChevronRight,CircleDot,LockKeyhole,Play,ShieldCheck,Sparkles,Target,Zap} from "lucide-react";
const steps=[["01","OBSERVE","Signals, context, data"],["02","DIAGNOSE","Problems, causes, opportunities"],["03","PRIORITIZE","Impact, confidence, effort"],["04","DECIDE","Evidence-backed recommendation"],["05","EXECUTE","Approved action through tools"],["06","LEARN","Measure outcome and improve"]];
const metrics=[["Decision latency","1.8s"],["Mission success","94.7%"],["Outcome attribution","91%"],["Execution safety","99.98%"]];
export default function Home(){const [running,setRunning]=useState(false);return <main>
<nav><div className="brand"><span className="mark"><BrainCircuit size={19}/></span><span>CORE ENGINE</span></div><div className="navlinks"><a href="#engine">Engine</a><a href="#architecture">Architecture</a><a href="#products">Products</a><a href="#quality">Quality</a></div><button className="navbtn" onClick={()=>setRunning(true)}>{running?"Engine running":"Run engine"} <ArrowRight size={16}/></button></nav>
<section className="hero"><div className="eyebrow"><span className="pulse"/> AI BUSINESS OPERATING SYSTEM <span className="line"/></div><h1>Turn business signals<br/><em>into intelligent action.</em></h1><p className="lead">Core Engine is the intelligence layer for products that need to understand what is happening, decide what matters next, execute approved actions, and learn from measurable outcomes.</p><div className="actions"><button className="primary" onClick={()=>setRunning(true)}><Play size={17} fill="currentColor"/> {running?"Running intelligence loop":"Run intelligence loop"}</button><a className="secondary" href="#architecture">Explore architecture <ChevronRight size={17}/></a></div><div className="status"><span className="dot"/> SYSTEM READY <span>•</span> 8 intelligence layers <span>•</span> human approval gates</div></section>
<section id="engine" className="loop"><div className="sectionhead"><span>THE INTELLIGENCE LOOP</span><h2>From signal to outcome.</h2></div><div className="steps">{steps.map(([n,t,d],i)=><div className={"step "+(running&&i<5?"active":"")} key={n}><div className="num">{n}</div><div className="stepicon">{i===0?<CircleDot size={18}/>:i===1?<Target size={18}/>:i===2?<Sparkles size={18}/>:i===3?<BrainCircuit size={18}/>:i===4?<Zap size={18}/>:<CheckCircle2 size={18}/>}</div><h3>{t}</h3><p>{d}</p></div>)}</div></section>
<section id="architecture" className="architecture"><div className="sectionhead"><span>CORE ARCHITECTURE</span><h2>One intelligence layer.<br/>Many products.</h2></div><div className="archgrid"><div className="corecard"><div className="orb"><BrainCircuit size={42}/></div><span className="tag">AI CORE</span><h3>Decision intelligence</h3><p>Context, evidence, reasoning, prioritization and recommendations in a structured decision contract.</p><div className="chips"><span>Context</span><span>Reasoning</span><span>Confidence</span><span>Evidence</span></div></div><div className="layers">{["Context Engine","Decision Center","Mission Engine","Approval Gate","Execution Layer","Outcome Engine","Learning System"].map((x,i)=><div className="layer" key={x}><b>{String(i+1).padStart(2,"0")}</b><span>{x}</span><ChevronRight size={15}/></div>)}</div></div></section>
<section id="products" className="products"><div className="sectionhead"><span>PRODUCT ECOSYSTEM</span><h2>Built once. Applied everywhere.</h2></div><div className="productgrid">{[["GROWTH ADVISOR","Business growth OS","Diagnose growth constraints and create measurable missions."],["WEBSITE BUILDER","Active business surface","Turn websites into continuously optimized growth assets."],["INVESTOR INTELLIGENCE","Opportunity analysis","Screen markets, companies, scenarios and risk with the same core."],["VERTICAL AGENTS","Specialized intelligence","Sales, hospitality, marketing, e-commerce and operations agents."]].map(([a,b,c])=><article key={a}><span>{a}</span><h3>{b}</h3><p>{c}</p><ArrowRight size={18}/></article>)}</div></section>
<section id="quality" className="quality"><div><span className="tag">PRODUCTION CONTROL</span><h2>Intelligence with<br/><em>guardrails.</em></h2><p>Every high-impact action passes through explicit authorization, tool permissions, execution state and outcome measurement.</p><div className="security"><div><ShieldCheck size={21}/><span>Least privilege</span></div><div><LockKeyhole size={21}/><span>Approval gates</span></div><div><CheckCircle2 size={21}/><span>Audit trail</span></div></div></div><div className="metrics">{metrics.map(([a,b])=><div key={a}><span>{a}</span><strong>{b}</strong></div>)}</div></section>
<footer><div className="brand"><span className="mark"><BrainCircuit size={17}/></span><span>CORE ENGINE</span></div><span>AI Decision & Execution Infrastructure</span><span>© 2026</span></footer>
</main>}