"use client";
import {useState} from "react";
import {ArrowRight,BrainCircuit,CheckCircle2,ChevronRight,LockKeyhole,Play,ShieldCheck,Sparkles,Zap,Loader2,XCircle,Activity} from "lucide-react";
import type {EngineResponse,MissionActionResponse,TraceStep} from "@/lib/api-contracts";
const scenarios={Growth:[{name:"conversion_rate",value:"2.8%",source:"analytics"},{name:"traffic",value:"+18%",source:"analytics"},{name:"checkout_dropoff",value:"41%",source:"funnel"}],Sales:[{name:"qualified_leads",value:"-14%",source:"CRM"},{name:"response_time",value:"11h",source:"CRM"},{name:"win_rate",value:"18%",source:"sales"}],Operations:[{name:"order_backlog",value:"+27%",source:"operations"},{name:"cycle_time",value:"3.4d",source:"ERP"},{name:"capacity",value:"82%",source:"workforce"}]} as const;
type Scenario=keyof typeof scenarios;
export default function Home(){const[running,setRunning]=useState(false),[result,setResult]=useState<EngineResponse|null>(null),[scenario,setScenario]=useState<Scenario>("Growth"),[busy,setBusy]=useState(""),[error,setError]=useState("");
async function run(){if(running)return;setRunning(true);setError("");try{const r=await fetch("/api/engine",{method:"POST",headers:{"Content-Type":"application/json","Accept":"application/json"},body:JSON.stringify({signals:scenarios[scenario]})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Engine request failed");setResult(d)}catch(e){setError(e instanceof Error?e.message:"Engine request failed")}finally{setRunning(false)}}
async function action(a:string){if(!result?.mission?.id)return;setBusy(a);setError("");try{const r=await fetch("/api/mission",{method:"POST",headers:{"Content-Type":"application/json","Accept":"application/json"},body:JSON.stringify({id:result.mission.id,action:a,idempotencyKey:crypto.randomUUID()})});const d=await r.json() as MissionActionResponse;if(!r.ok)throw new Error(d.error||"Mission action failed");setResult(x=>x?{...x,mission:d.mission,state:d.mission?.state,trace:d.trace??x.trace}:x)}catch(e){setError(e instanceof Error?e.message:"Mission action failed")}finally{setBusy("")}}
const next=result?.mission?.state==="AWAITING_APPROVAL"?"approve":result?.mission?.state==="APPROVED"?"execute":result?.mission?.state==="EXECUTING"?"measure":result?.mission?.state==="MEASURING"?"complete":result?.mission?.state==="COMPLETED"?"learn":result?.mission?.state==="FAILED"?"retry":"";
return <main><nav><div className="brand"><span className="mark"><BrainCircuit size={19}/></span><span>CORE ENGINE</span></div><div className="navlinks"><a href="#engine">Engine</a><a href="#architecture">Architecture</a><a href="#control">Control</a><a href="#autonomous">101→112</a></div><button className="navbtn" onClick={run} disabled={running}>{running?<Loader2 size={15} className="spin"/>:<Play size={15}/>} {running?"Running":"Run engine"} <ArrowRight size={15}/></button></nav>
<section className="hero"><div className="eyebrow"><span className="pulse"/> AI BUSINESS OPERATING SYSTEM <span className="line"/></div><h1>Signals into<br/><em>intelligent action.</em></h1><p className="lead">Observe, diagnose, prioritize, decide, govern execution, measure outcomes and learn through one reusable intelligence core.</p><div className="actions"><button className="primary" onClick={run} disabled={running}><Play size={16}/>{running?"Running intelligence loop":"Run live intelligence demo"}</button><a className="secondary" href="#architecture">Explore system <ChevronRight size={16}/></a></div><div className="status" role="status" aria-live="polite"><span className="dot"/>{result?"DECISION + MISSION LIVE":"SYSTEM READY"} <span>•</span> fail-closed risk <span>•</span> human gate <span>•</span> measured outcomes</div>
<div className="demo-bar"><div className="demo-copy"><span className="tag">DEMO INPUT</span><b>Choose signal context</b><small>Same engine, different operating context.</small></div><div className="scenario-tabs">{(Object.keys(scenarios) as Scenario[]).map(s=><button key={s} className={scenario===s?"selected":""} aria-pressed={scenario===s} onClick={()=>setScenario(s)}><Activity size={13}/>{s}</button>)}</div><div className="signal-pills">{scenarios[scenario].map(s=><span key={s.name}><b>{s.name}</b>{s.value}<i>{s.source}</i></span>)}</div></div>
{result?.decision&&result.mission&&<section className="decision" aria-live="polite"><div className="decisiontop"><span className="tag">LIVE ENGINE OUTPUT</span><span className="approved">{result.mission.state}</span></div><h3>{result.decision.recommendation}</h3><p>{result.decision.diagnosis}</p><div className="decisiongrid"><div><small>CONFIDENCE</small><b>{Math.round(result.decision.confidence*100)}%</b></div><div><small>PRIORITY</small><b>{result.decision.priority}</b></div><div><small>SOURCE</small><b>{result.decision.reasoningSource}</b></div><div><small>MATRIX</small><b>{result.decision.decisionMatrix?.action??"—"}</b></div></div><div className="evidence"><span>Evidence</span>{result.decision.evidence.slice(0,6).map(x=><code key={x}>{x}</code>)}</div><div className="trace">{(result.trace??[]).map((x:TraceStep,i)=><span key={x.stage+i} className={i===(result.trace?.length??1)-1?"current":""}>{x.stage} · {x.status}</span>)}</div><div className="missionbar"><div><span>MISSION</span><b>{result.mission.objective}</b></div><button className="nextaction" disabled={!next||!!busy} onClick={()=>action(next)}>{busy?<Loader2 size={14} className="spin"/>:<Zap size={14}/>} {busy?"PROCESSING":next?next.toUpperCase():"MISSION COMPLETE"}</button></div></section>}
{error&&<div className="error" role="alert"><XCircle size={16}/>{error}</div>}</section>
<section id="engine" className="loop"><div className="sectionhead"><span>INTELLIGENCE LOOP</span><h2>One closed loop from signal to outcome.</h2></div><div className="steps">{["OBSERVE","DIAGNOSE","PRIORITIZE","DECIDE","EXECUTE","LEARN"].map((x,i)=><div className={"step "+(result&&i<4?"active":"")} key={x}><div className="num">0{i+1}</div><Sparkles size={18}/><h3>{x}</h3><p>{["Signals, context, data","Problems and causes","Impact, confidence, effort","Evidence-backed recommendation","Approved action boundary","Measured outcome reuse"][i]}</p></div>)}</div></section>
<section id="architecture" className="architecture"><div className="sectionhead"><span>CORE ARCHITECTURE</span><h2>Reusable intelligence behind every product.</h2></div><div className="archgrid"><div className="corecard"><div className="orb"><BrainCircuit size={40}/></div><span className="tag">AI CORE · 1.0</span><h3>Decision intelligence</h3><p>Typed decisions, deterministic safety, evidence, policy and measurable mission state.</p><div className="chips"><span>Context</span><span>Reasoning</span><span>Risk</span><span>Policy</span><span>Audit</span><span>Learning</span></div></div><div className="layers">{["Context Engine","Decision Center","Mission Engine","Approval Gate","Execution Layer","Outcome Engine","Learning System"].map((x,i)=><div className="layer" key={x}><b>{String(i+1).padStart(2,"0")}</b><div><strong>{x}</strong><small>Structured, observable control surface</small></div><ChevronRight size={15}/></div>)}</div></div></section>
<section id="control" className="control"><div className="sectionhead"><span>CONTROL CENTER</span><h2>Autonomy with explicit boundaries.</h2></div><div className="controlgrid">{[["REASON","AI proposes"],["GOVERN","Human approves"],["ACT","Tools execute"],["LEARN","Outcomes teach"]].map(([a,b])=><article key={a}><div className="controlicon"><LockKeyhole size={19}/></div><span>{a}</span><h3>{b}</h3><p>Policy, state and evidence determine what can happen next.</p></article>)}</div></section>
<section id="autonomous" className="programfield"><div className="sectionhead"><span>AUTONOMOUS PROGRAM · 101 → 112</span><h2>Continuation, recovery, validation and dynamic expansion.</h2></div><div className="programrail">{["BRIDGE","BOUNDARY","CHECKPOINT","EVIDENCE","RESUME","SCOPE","EXECUTE","EVALUATE","CONSISTENCY","APPROVAL","CONTINUATION","EXPAND"].map((x,i)=><div className={"programnode "+(i===11?"final":"")} key={x}><small>{101+i}</small><strong>{x}</strong><span>stage</span></div>)}</div></section>
<section className="quality"><div><span className="tag">PRODUCTION CONTROL</span><h2>Evidence before action.</h2><p>Fail-closed risk gates, explicit actor policy, idempotency, signed audit capability and durable persistence contracts.</p></div><div className="metrics"><div><span>Mission states</span><strong>12</strong></div><div><span>Program stages</span><strong>12</strong></div><div><span>Control</span><strong>HUMAN GATE</strong></div><div><span>Runtime</span><strong>READY</strong></div></div></section><footer><div className="brand"><span className="mark"><BrainCircuit size={17}/></span><span>CORE ENGINE</span></div><span>AI Decision & Execution Infrastructure</span><span>© 2026</span></footer></main>}
