export const A2A_PROTOCOL_VERSION = "a2a-v1" as const;
export const A2A_MILESTONES = {
  M226:"agent identity",M227:"capability exchange",M228:"task negotiation",M229:"delegation",M230:"handoff",
  M231:"trust handshake",M232:"authorization",M233:"tenant isolation",M234:"message envelope",M235:"correlation",
  M236:"remote verification",M237:"remote outcome",M238:"remote learning",M239:"protocol versioning",M240:"compatibility",
  M241:"federation policy",M242:"arbitration",M243:"route optimization",M244:"budget routing",M245:"rate limiting",
  M246:"replay protection",M247:"audit",M248:"incident control",M249:"kill switch",M250:"interoperability control plane"
} as const;

export type AgentIdentity={id:string;tenantId:string;name:string;protocolVersion:string;capabilities:string[];trustDomain:string};
export type CapabilityOffer={agentId:string;tenantId:string;capability:string;version:string;inputKeys:string[];outputKeys:string[];risk:"LOW"|"MEDIUM"|"HIGH"|"CRITICAL"};
export type TaskRequest={taskId:string;tenantId:string;requesterId:string;capability:string;input:Record<string,unknown>;budget:{maxTokens:number;maxCost:number};deadline:number};
export type NegotiatedTask=TaskRequest & {providerId:string;status:"NEGOTIATED"|"REJECTED";agreedCost:number;protocolVersion:string};
export type Delegation={delegationId:string;taskId:string;fromAgentId:string;toAgentId:string;tenantId:string;scope:string;expiresAt:number;approvalId:string};
export type Handoff={handoffId:string;taskId:string;fromAgentId:string;toAgentId:string;tenantId:string;reason:string;correlationId:string};
export type TrustHandshake={nonce:string;initiatorId:string;responderId:string;tenantId:string;protocolVersion:string;verified:boolean};
export type Authorization={authorizationId:string;tenantId:string;agentId:string;taskId:string;capability:string;approved:boolean;expiresAt:number};
export type A2AEnvelope={version:string;messageId:string;correlationId:string;tenantId:string;sender:AgentIdentity;recipientId:string;type:"TASK"|"DELEGATION"|"HANDOFF"|"OUTCOME"|"LEARNING";payload:Record<string,unknown>;createdAt:number;nonce:string};
export type RemoteVerification={correlationId:string;verified:boolean;checks:string[];evidenceHash:string};
export type RemoteOutcome={correlationId:string;status:"SUCCEEDED"|"FAILED"|"REJECTED";verified:boolean;output:Record<string,unknown>;cost:number};
export type LearningSignal={correlationId:string;verifiedOutcomeId:string;eligible:boolean;reason:string;features:Record<string,unknown>};
export type FederationPolicy={tenantId:string;allowedTrustDomains:string[];allowedProtocols:string[];maxRemoteRisk:"LOW"|"MEDIUM"|"HIGH";requireApproval:boolean};
export type Route={providerId:string;latencyMs:number;cost:number;capacity:number;trustScore:number;compatible:boolean};
export type Incident={incidentId:string;tenantId:string;correlationId?:string;severity:"LOW"|"MEDIUM"|"HIGH"|"CRITICAL";reason:string;status:"OPEN"|"CONTAINED"|"RESOLVED"};
export type ControlPlaneState={killed:boolean;incidents:Incident[];seenNonces:Set<string>;rateWindows:Map<string,{startedAt:number;count:number}>};

export function createControlPlaneState():ControlPlaneState{return{killed:false,incidents:[],seenNonces:new Set(),rateWindows:new Map()};}
export function assertTenantIsolation(expectedTenant:string, actualTenant:string){if(!expectedTenant||expectedTenant!==actualTenant)throw new Error("TENANT_ISOLATION_VIOLATION");}
export function assertProtocolCompatible(local:string, remote:string){if(local!==remote)throw new Error("PROTOCOL_INCOMPATIBLE");return true;}
export function assertFederationAllowed(policy:FederationPolicy, identity:AgentIdentity, risk:CapabilityOffer["risk"]){if(!policy.allowedTrustDomains.includes(identity.trustDomain)||!policy.allowedProtocols.includes(identity.protocolVersion))throw new Error("FEDERATION_BLOCKED");if(policy.maxRemoteRisk==="LOW"&&risk!=="LOW")throw new Error("FEDERATION_RISK_BLOCKED");if(policy.maxRemoteRisk==="MEDIUM"&&risk==="HIGH")throw new Error("FEDERATION_RISK_BLOCKED");if(policy.maxRemoteRisk!=="HIGH"&&risk==="CRITICAL")throw new Error("FEDERATION_RISK_BLOCKED");}
export function negotiateTask(task:TaskRequest, requester:AgentIdentity, provider:CapabilityOffer, now=Date.now()):NegotiatedTask{assertTenantIsolation(task.tenantId,provider.tenantId);assertProtocolCompatible(requester.protocolVersion,A2A_PROTOCOL_VERSION);if(provider.capability!==task.capability)throw new Error("CAPABILITY_UNAVAILABLE");if(task.deadline<=now)throw new Error("TASK_DEADLINE_EXPIRED");const agreedCost=Math.min(task.budget.maxCost,Math.max(0,task.input.cost as number||0));return{...task,providerId:provider.agentId,status:"NEGOTIATED",agreedCost,protocolVersion:A2A_PROTOCOL_VERSION};}
export function authorizeTask(task:NegotiatedTask, approvalId:string, policy:FederationPolicy, now=Date.now()):Authorization{if(policy.requireApproval&&!approvalId)throw new Error("APPROVAL_REQUIRED");if(task.status!=="NEGOTIATED")throw new Error("TASK_NOT_NEGOTIATED");return{authorizationId:"auth-"+task.taskId,tenantId:task.tenantId,agentId:task.providerId,taskId:task.taskId,capability:task.capability,approved:true,expiresAt:Math.min(task.deadline,now+300000)};}
export function delegateTask(task:NegotiatedTask, from:AgentIdentity, to:AgentIdentity, authorization:Authorization, now=Date.now()):Delegation{assertTenantIsolation(task.tenantId,to.tenantId);if(!authorization.approved||authorization.taskId!==task.taskId)throw new Error("AUTHORIZATION_INVALID");return{delegationId:"del-"+task.taskId+"-"+to.id,taskId:task.taskId,fromAgentId:from.id,toAgentId:to.id,tenantId:task.tenantId,scope:task.capability,expiresAt:authorization.expiresAt,approvalId:authorization.authorizationId};}
export function createHandoff(taskId:string,from:AgentIdentity,to:AgentIdentity,reason:string,correlationId:string):Handoff{assertTenantIsolation(from.tenantId,to.tenantId);return{handoffId:"handoff-"+correlationId,taskId,fromAgentId:from.id,toAgentId:to.id,tenantId:from.tenantId,reason,correlationId};}
export function createEnvelope(sender:AgentIdentity,recipientId:string,type:A2AEnvelope["type"],payload:Record<string,unknown>,correlationId:string,nonce:string,messageId="msg-"+correlationId):A2AEnvelope{return{version:A2A_PROTOCOL_VERSION,messageId,correlationId,tenantId:sender.tenantId,sender,recipientId,type,payload,createdAt:Date.now(),nonce};}
export function assertReplaySafe(state:ControlPlaneState,nonce:string){if(state.seenNonces.has(nonce))throw new Error("REPLAY_DETECTED");state.seenNonces.add(nonce);return true;}
export function enforceRateLimit(state:ControlPlaneState,key:string,limit:number,windowMs:number,now=Date.now()){const current=state.rateWindows.get(key);if(!current||now-current.startedAt>=windowMs){state.rateWindows.set(key,{startedAt:now,count:1});return true;}if(current.count>=limit)throw new Error("RATE_LIMITED");current.count++;return true;}
export function verifyRemoteOutcome(correlationId:string,outcome:RemoteOutcome,expectedTenant:string,expectedCorrelationId:string):RemoteVerification{assertTenantIsolation(expectedTenant,expectedTenant);if(correlationId!==expectedCorrelationId||outcome.correlationId!==correlationId)throw new Error("CORRELATION_MISMATCH");if(!outcome.verified)throw new Error("REMOTE_OUTCOME_UNVERIFIED");const evidenceHash=JSON.stringify({correlationId,outcome});return{correlationId,verified:true,checks:["tenant","correlation","outcome-verification"],evidenceHash};}
export function buildLearningSignal(outcome:RemoteOutcome,verification:RemoteVerification):LearningSignal{if(!verification.verified||!outcome.verified)return{correlationId:outcome.correlationId,verifiedOutcomeId:"",eligible:false,reason:"VERIFIED_OUTCOME_REQUIRED",features:{}};return{correlationId:outcome.correlationId,verifiedOutcomeId:"outcome-"+outcome.correlationId,eligible:true,reason:"VERIFIED_REMOTE_OUTCOME",features:{status:outcome.status,cost:outcome.cost}};}
export function optimizeRoute(routes:Route[],budget:number){const eligible=routes.filter(r=>r.compatible&&r.cost<=budget&&r.capacity>0);if(!eligible.length)throw new Error("NO_ROUTE");return[...eligible].sort((a,b)=>(b.trustScore-a.trustScore)||(a.cost-b.cost)||(a.latencyMs-b.latencyMs))[0];}
export function arbitrate(routes:Route[],budget:number){return optimizeRoute(routes,budget);}
export function routeWithinBudget(route:Route,budget:number){if(route.cost>budget)throw new Error("BUDGET_EXCEEDED");return route;}
export function openIncident(state:ControlPlaneState,input:Omit<Incident,"status">):Incident{const incident={...input,status:"OPEN" as const};state.incidents.push(incident);return incident;}
export function containIncident(state:ControlPlaneState,incidentId:string){const i=state.incidents.find(x=>x.incidentId===incidentId);if(!i)throw new Error("INCIDENT_NOT_FOUND");i.status="CONTAINED";return i;}
export function resolveIncident(state:ControlPlaneState,incidentId:string){const i=state.incidents.find(x=>x.incidentId===incidentId);if(!i)throw new Error("INCIDENT_NOT_FOUND");i.status="RESOLVED";return i;}
export function assertExecutionEnabled(state:ControlPlaneState){if(state.killed)throw new Error("KILL_SWITCH_ACTIVE");return true;}
export function setKillSwitch(state:ControlPlaneState,active:boolean){state.killed=active;return state.killed;}
export function registerTrustHandshake(initiator:AgentIdentity,responder:AgentIdentity,nonce:string):TrustHandshake{assertTenantIsolation(initiator.tenantId,responder.tenantId);assertProtocolCompatible(initiator.protocolVersion,responder.protocolVersion);return{nonce,initiatorId:initiator.id,responderId:responder.id,tenantId:initiator.tenantId,protocolVersion:initiator.protocolVersion,verified:true};}
export function controlPlaneHealth(state:ControlPlaneState){return{killed:state.killed,openIncidents:state.incidents.filter(i=>i.status!=="RESOLVED").length,replayCacheSize:state.seenNonces.size,rateLimitKeys:state.rateWindows.size,protocol:A2A_PROTOCOL_VERSION,milestones:Object.keys(A2A_MILESTONES).length};}
