import { createHash } from "node:crypto";
export const AGENT_ECONOMY_VERSION="aecon-v1" as const;
export const AECON_STAGES=[
{id:276,name:"SKILL_QUALITY_SCORE",phase:"QUALITY"},{id:277,name:"SKILL_SUCCESS_RATE_SCORE",phase:"QUALITY"},{id:278,name:"SKILL_COST_SCORE",phase:"ECONOMY"},{id:279,name:"SKILL_LATENCY_SCORE",phase:"ECONOMY"},{id:280,name:"SKILL_RISK_ADJUSTED_VALUE",phase:"OPTIMIZATION"},{id:281,name:"SKILL_PROVIDER_VALUE",phase:"OPTIMIZATION"},{id:282,name:"SKILL_REPUTATION_SCORE",phase:"TRUST"},{id:283,name:"SKILL_CERTIFICATION_WEIGHT",phase:"TRUST"},{id:284,name:"SKILL_DEMAND_SIGNAL",phase:"MARKET"},{id:285,name:"SKILL_SUPPLY_SIGNAL",phase:"MARKET"},{id:286,name:"SKILL_PRICE_MODEL",phase:"ECONOMY"},{id:287,name:"SKILL_VALUE_MODEL",phase:"ECONOMY"},{id:288,name:"SKILL_ROUTE_OPTIMIZER",phase:"OPTIMIZATION"},{id:289,name:"SKILL_BUNDLE_OPTIMIZER",phase:"COMPOSITION"},{id:290,name:"SKILL_CHAIN_VALUE",phase:"COMPOSITION"},{id:291,name:"SKILL_REPLACEMENT_ENGINE",phase:"OPTIMIZATION"},{id:292,name:"SKILL_MARKETPLACE_RANKING",phase:"REGISTRY"},{id:293,name:"SKILL_REPUTATION_MEMORY",phase:"MEMORY"},{id:294,name:"SKILL_ECONOMIC_FEEDBACK",phase:"LEARNING"},{id:295,name:"SKILL_DEMAND_FORECAST",phase:"PREDICTION"},{id:296,name:"SKILL_CAPACITY_PLANNING",phase:"PLANNING"},{id:297,name:"SKILL_ECONOMIC_GOVERNANCE",phase:"GOVERNANCE"},{id:298,name:"SKILL_OPTIMIZATION_CERTIFICATION",phase:"CERTIFICATION"},{id:299,name:"SKILL_ECONOMY_READINESS",phase:"READINESS"},{id:300,name:"UNIVERSAL_AGENT_ECONOMY_CONTROL_PLANE",phase:"CONTROL"}] as const;
export type SkillEconomyInput={quality:number;successRate:number;cost:number;latencyMs:number;risk:number;trust:number;certified:boolean;demand:number;supply:number};
const clamp=(x:number)=>Math.max(0,Math.min(1,Number.isFinite(x)?x:0));const sha=(x:unknown)=>createHash("sha256").update(JSON.stringify(x)).digest("hex");
export function scoreSkillEconomy(x:SkillEconomyInput){const quality=clamp(x.quality),success=clamp(x.successRate),cost=1/(1+Math.max(0,x.cost)),latency=1/(1+Math.max(0,x.latencyMs)/1000),risk=1-clamp(x.risk),trust=clamp(x.trust),cert=x.certified?1:.5,demand=clamp(x.demand),supply=clamp(x.supply);const scarcity=demand/(demand+supply+.001);const value=quality*.2+success*.25+cost*.1+latency*.05+risk*.1+trust*.1+cert*.1+scarcity*.1;return{value,scarcity,quality,success,cost,latency,risk,trust,cert};}
export function rankSkills(items:Array<SkillEconomyInput&{id:string}>){return items.map(x=>({id:x.id,score:scoreSkillEconomy(x)})).sort((a,b)=>b.score.value-a.score.value);}
export function optimizeRoute(routes:Array<{id:string;skills:string[];cost:number;latencyMs:number;successRate:number;risk:number;trust:number}>){return routes.map(r=>({...r,utility:clamp(r.successRate*.45+r.trust*.2+(1-r.risk)*.2+1/(1+r.cost)*.1+1/(1+r.latencyMs/1000)*.05)})).sort((a,b)=>b.utility-a.utility);}
export function bundleValue(items:Array<{value:number;cost:number;success:number}>){if(!items.length)return{value:0,cost:0,success:0};const cost=items.reduce((a,b)=>a+b.cost,0),success=items.reduce((a,b)=>a+b.success,0)/items.length;return{value:items.reduce((a,b)=>a+b.value,0)+success*.2,cost,success};}
export function readiness(input:{certified:boolean;ranked:boolean;governed:boolean;learningConnected:boolean}){const ready=Object.values(input).every(Boolean);return{ready,reasons:Object.entries(input).filter(([,v])=>!v).map(([k])=>k.toUpperCase()+"_MISSING"),integrity:sha(input)};}
