import { createHash } from "node:crypto";
export const AGENT_LEARNING_VERSION="ale-v1" as const;
export const ALE_STAGES=[
{id:251,name:"OBJECTIVE_OUTCOME_MEMORY",phase:"MEMORY"},{id:252,name:"CONTEXT_OUTCOME_MEMORY",phase:"MEMORY"},{id:253,name:"SKILL_OUTCOME_MEMORY",phase:"MEMORY"},{id:254,name:"PROVIDER_OUTCOME_MEMORY",phase:"MEMORY"},{id:255,name:"COST_OUTCOME_MEMORY",phase:"MEMORY"},{id:256,name:"LATENCY_OUTCOME_MEMORY",phase:"MEMORY"},{id:257,name:"FAILURE_OUTCOME_MEMORY",phase:"MEMORY"},{id:258,name:"EVIDENCE_QUALITY_MEMORY",phase:"MEMORY"},{id:259,name:"HUMAN_FEEDBACK_MEMORY",phase:"MEMORY"},{id:260,name:"AGENT_EVALUATION_DATASET",phase:"EVALUATION"},{id:261,name:"OBJECTIVE_SUCCESS_METRIC",phase:"EVALUATION"},{id:262,name:"SKILL_SUCCESS_METRIC",phase:"EVALUATION"},{id:263,name:"PROVIDER_SUCCESS_METRIC",phase:"EVALUATION"},{id:264,name:"COST_EFFICIENCY_METRIC",phase:"EVALUATION"},{id:265,name:"LATENCY_EFFICIENCY_METRIC",phase:"EVALUATION"},{id:266,name:"FAILURE_RATE_METRIC",phase:"EVALUATION"},{id:267,name:"EVIDENCE_COMPLETENESS_METRIC",phase:"EVALUATION"},{id:268,name:"HUMAN_OVERRIDE_METRIC",phase:"EVALUATION"},{id:269,name:"AGENT_CALIBRATION_ENGINE",phase:"CALIBRATION"},{id:270,name:"AGENT_AB_EXPERIMENT_ENGINE",phase:"EXPERIMENT"},{id:271,name:"AGENT_REGRESSION_ENGINE",phase:"QUALITY"},{id:272,name:"AGENT_POLICY_EVALUATOR",phase:"GOVERNANCE"},{id:273,name:"AGENT_LEARNING_UPDATE",phase:"LEARNING"},{id:274,name:"AGENT_REPLAN_SIGNAL_ENGINE",phase:"ADAPTATION"},{id:275,name:"CLOSED_LOOP_AGENT_LEARNING",phase:"LEARNING"}] as const;
export type Outcome={objective:string;success:number;cost:number;latencyMs:number;failureClass?:string;evidenceQuality:number;humanOverride:boolean;skillId?:string;providerId?:string;createdAt:string};
export type LearningProfile={attempts:number;successRate:number;meanCost:number;meanLatencyMs:number;evidenceQuality:number;overrideRate:number;confidence:number;lastUpdated:string};
const now=()=>new Date().toISOString();const clamp=(x:number)=>Math.max(0,Math.min(1,Number.isFinite(x)?x:0));const sha=(x:unknown)=>createHash("sha256").update(JSON.stringify(x)).digest("hex");
export function recordOutcome(input:Omit<Outcome,"createdAt">):Outcome{return{...input,success:clamp(input.success),cost:Math.max(0,input.cost),latencyMs:Math.max(0,input.latencyMs),evidenceQuality:clamp(input.evidenceQuality),createdAt:now()};}
export function aggregateLearning(outcomes:Outcome[]):LearningProfile{if(!outcomes.length)return{attempts:0,successRate:.5,meanCost:0,meanLatencyMs:0,evidenceQuality:.5,overrideRate:0,confidence:0,lastUpdated:now()};const n=outcomes.length;return{attempts:n,successRate:outcomes.reduce((a,o)=>a+o.success,0)/n,meanCost:outcomes.reduce((a,o)=>a+o.cost,0)/n,meanLatencyMs:outcomes.reduce((a,o)=>a+o.latencyMs,0)/n,evidenceQuality:outcomes.reduce((a,o)=>a+o.evidenceQuality,0)/n,overrideRate:outcomes.filter(o=>o.humanOverride).length/n,confidence:Math.min(1,1-Math.exp(-n/20)),lastUpdated:now()};}
export function calibrationError(predicted:number,actual:number){return Math.abs(clamp(predicted)-clamp(actual));}
export function compareAgents(a:LearningProfile,b:LearningProfile){const score=p=>p.successRate*.5+p.evidenceQuality*.2+(1-p.overrideRate)*.15+Math.min(1,p.attempts/20)*.15;return{winner:Math.abs(score(a)-score(b))<.03?"TIE":score(a)>score(b)?"A":"B",delta:score(a)-score(b)};}
export function regressionSignal(baseline:LearningProfile,current:LearningProfile){return{regressed:current.attempts>=5&&baseline.attempts>=5&&current.successRate<baseline.successRate-.1,successDelta:current.successRate-baseline.successRate,costDelta:current.meanCost-baseline.meanCost};}
export function buildReplanSignal(profile:LearningProfile){if(profile.successRate<.5)return{replan:true,reason:"LOW_SUCCESS_RATE"};if(profile.evidenceQuality<.6)return{replan:true,reason:"LOW_EVIDENCE_QUALITY"};if(profile.overrideRate>.5)return{replan:true,reason:"HIGH_HUMAN_OVERRIDE"};return{replan:false,reason:"LEARNING_STABLE"};}
export function learningDigest(outcomes:Outcome[]){const payload={version:AGENT_LEARNING_VERSION,count:outcomes.length,profile:aggregateLearning(outcomes)};return{...payload,integrity:sha(payload)};}
