import { createHash } from "node:crypto";
export const AGENT_INTEROP_VERSION="aio-v1" as const;
export const AIO_STAGES=[
{id:226,name:"AGENT_CARD_CONTRACT",phase:"DISCOVERY"},{id:227,name:"A2A_MESSAGE_ENVELOPE",phase:"INTEROPERABILITY"},{id:228,name:"AGENT_IDENTITY",phase:"SECURITY"},{id:229,name:"DELEGATION_SCOPE",phase:"GOVERNANCE"},{id:230,name:"EXTERNAL_AGENT_DISCOVERY",phase:"DISCOVERY"},{id:231,name:"AGENT_CAPABILITY_NEGOTIATION",phase:"NEGOTIATION"},{id:232,name:"AGENT_SKILL_HANDSHAKE",phase:"NEGOTIATION"},{id:233,name:"AGENT_PROVIDER_REPUTATION",phase:"TRUST"},{id:234,name:"AGENT_EVIDENCE_EXCHANGE",phase:"EVIDENCE"},{id:235,name:"AGENT_OUTCOME_EXCHANGE",phase:"LEARNING"},{id:236,name:"CROSS_AGENT_APPROVAL",phase:"CONTROL"},{id:237,name:"DELEGATED_EXECUTION_BOUNDARY",phase:"EXECUTION"},{id:238,name:"DELEGATION_COST_GUARD",phase:"GOVERNANCE"},{id:239,name:"DELEGATION_RISK_GUARD",phase:"GOVERNANCE"},{id:240,name:"AGENT_FALLBACK_ROUTER",phase:"RECOVERY"},{id:241,name:"AGENT_FAILURE_PROTOCOL",phase:"RECOVERY"},{id:242,name:"AGENT_SESSION_CONTINUITY",phase:"RUNTIME"},{id:243,name:"AGENT_REPLAY_INTEGRITY",phase:"INTEGRITY"},{id:244,name:"AGENT_TRUST_SCORE",phase:"TRUST"},{id:245,name:"AGENT_REPUTATION_MEMORY",phase:"MEMORY"},{id:246,name:"AGENT_COMPATIBILITY_ENGINE",phase:"LIFECYCLE"},{id:247,name:"AGENT_PROTOCOL_VERSIONING",phase:"LIFECYCLE"},{id:248,name:"AGENT_DELEGATION_AUDIT",phase:"AUDIT"},{id:249,name:"AGENT_INTEROP_CERTIFICATION",phase:"CERTIFICATION"},{id:250,name:"UNIVERSAL_AGENT_INTEROP_CONTROL_PLANE",phase:"CONTROL"}] as const;
export type AgentCard={id:string;name:string;version:string;description:string;skills:string[];domains:string[];endpoint?:string;protocols:string[];trustScore:number;status:"ACTIVE"|"BLOCKED"|"DEPRECATED"};
export type Delegation={delegationId:string;fromAgent:string;toAgent:string;objective:string;skills:string[];scope:string[];approvalId:string;maxCost:number;risk:"LOW"|"MEDIUM"|"HIGH"|"CRITICAL";createdAt:string;integrity:string};
const now=()=>new Date().toISOString();const sha=(x:unknown)=>createHash("sha256").update(JSON.stringify(x)).digest("hex");const clean=(x:unknown[],n=50)=>[...new Set(x.map(String).map(v=>v.trim()).filter(Boolean))].slice(0,n);
export function createAgentCard(input:Partial<AgentCard>&Pick<AgentCard,"id"|"name"|"description">):AgentCard{return{id:input.id.trim(),name:input.name.trim(),version:input.version||"1.0.0",description:input.description.trim().slice(0,1000),skills:clean(input.skills||[],100),domains:clean(input.domains||["general"],30),endpoint:input.endpoint?.trim(),protocols:clean(input.protocols||["A2A"],20),trustScore:Math.max(0,Math.min(1,input.trustScore??0.5)),status:input.status||"ACTIVE"};}
export function validateAgentCard(card:AgentCard){const errors:string[]=[];if(!card.id||!card.name)errors.push("IDENTITY_REQUIRED");if(!card.version)errors.push("VERSION_REQUIRED");if(!card.skills.length)errors.push("SKILLS_REQUIRED");if(!card.protocols.length)errors.push("PROTOCOL_REQUIRED");if(card.trustScore<0||card.trustScore>1)errors.push("TRUST_INVALID");return{valid:!errors.length,errors};}
export function negotiateCapabilities(local:AgentCard,remote:AgentCard){const commonSkills=local.skills.filter(s=>remote.skills.includes(s));const commonDomains=local.domains.filter(d=>remote.domains.includes(d));const protocol=local.protocols.find(p=>remote.protocols.includes(p));return{compatible:Boolean(protocol&&commonSkills.length),protocol,commonSkills,commonDomains,trust:Math.min(local.trustScore,remote.trustScore)};}
export function authorizeDelegation(input:{from:AgentCard;to:AgentCard;objective:string;skills:string[];scope:string[];approvalId:string;maxCost:number;risk:"LOW"|"MEDIUM"|"HIGH"|"CRITICAL"}){if(!input.approvalId.trim())return{allowed:false,reason:"APPROVAL_REQUIRED"};if(input.from.status!=="ACTIVE"||input.to.status!=="ACTIVE")return{allowed:false,reason:"AGENT_INACTIVE"};const n=negotiateCapabilities(input.from,input.to);if(!n.compatible)return{allowed:false,reason:"CAPABILITY_NEGOTIATION_FAILED"};if(input.skills.some(s=>!n.commonSkills.includes(s)))return{allowed:false,reason:"SKILL_NOT_NEGOTIATED"};if(input.risk==="CRITICAL"&&input.to.trustScore<0.9)return{allowed:false,reason:"TRUST_TOO_LOW"};return{allowed:true,reason:"DELEGATION_ALLOWED",negotiation:n};}
export function buildDelegation(input:{from:AgentCard;to:AgentCard;objective:string;skills:string[];scope:string[];approvalId:string;maxCost:number;risk:"LOW"|"MEDIUM"|"HIGH"|"CRITICAL"}):Delegation{const auth=authorizeDelegation(input);if(!auth.allowed)throw new Error(auth.reason);const base={delegationId:"dlg_"+sha({from:input.from.id,to:input.to.id,objective:input.objective,approvalId:input.approvalId}).slice(0,24),fromAgent:input.from.id,toAgent:input.to.id,objective:input.objective.trim().slice(0,1000),skills:clean(input.skills,50),scope:clean(input.scope,50),approvalId:input.approvalId,maxCost:Math.max(0,input.maxCost),risk:input.risk,createdAt:now()};return{...base,integrity:sha(base)};}
export function verifyDelegation(d:Delegation){const base={delegationId:d.delegationId,fromAgent:d.fromAgent,toAgent:d.toAgent,objective:d.objective,skills:d.skills,scope:d.scope,approvalId:d.approvalId,maxCost:d.maxCost,risk:d.risk,createdAt:d.createdAt};return sha(base)===d.integrity;}
export function trustScore(input:{availability:number;successRate:number;evidenceQuality:number;policyViolations:number}){const score=Math.max(0,Math.min(1,input.availability*.25+input.successRate*.4+input.evidenceQuality*.35-input.policyViolations*.1));return score;}
export function routeDelegation(cards:AgentCard[],requiredSkills:string[],domain:string){return cards.filter(c=>c.status==="ACTIVE"&&c.domains.includes(domain)&&requiredSkills.every(s=>c.skills.includes(s))).sort((a,b)=>b.trustScore-a.trustScore);}
