import{createHash}from"node:crypto";
export const AGENT_INTEROP_VERSION="a2a-core-v1"as const;
export const A2A_STAGES=[[226,"AGENT_CARD_CONTRACT","INTEROPERABILITY"],[227,"AGENT_DISCOVERY_REGISTRY","DISCOVERY"],[228,"AGENT_CAPABILITY_ADVERTISEMENT","DISCOVERY"],[229,"AGENT_DELEGATION_CONTRACT","DELEGATION"],[230,"DELEGATION_SCOPE_ENGINE","SECURITY"],[231,"DELEGATION_APPROVAL_GATE","GOVERNANCE"],[232,"CROSS_AGENT_IDENTITY","IDENTITY"],[233,"CROSS_AGENT_AUTHORIZATION","SECURITY"],[234,"CROSS_AGENT_EVIDENCE","EVIDENCE"],[235,"CROSS_AGENT_RESULT_VERIFICATION","VALIDATION"],[236,"AGENT_REPUTATION_MEMORY","LEARNING"],[237,"AGENT_PROVIDER_HEALTH","PROVIDER"],[238,"AGENT_FALLBACK_DELEGATION","RECOVERY"],[239,"DELEGATION_COST_MODEL","OPTIMIZATION"],[240,"DELEGATION_RISK_MODEL","GOVERNANCE"],[241,"AGENT_NEGOTIATION_PROTOCOL","COORDINATION"],[242,"MULTI_AGENT_PLAN_MERGE","ORCHESTRATION"],[243,"CROSS_AGENT_MEMORY_SYNC","MEMORY"],[244,"AGENT_FAILURE_CLASSIFICATION","RECOVERY"],[245,"DELEGATION_RETRY_POLICY","RECOVERY"],[246,"AGENT_CONTRACT_VERSIONING","LIFECYCLE"],[247,"AGENT_REGRESSION_DETECTION","QUALITY"],[248,"AGENT_CERTIFICATION","CERTIFICATION"],[249,"AGENT_TRUST_SCORE","TRUST"],[250,"UNIVERSAL_AGENT_INTEROPERABILITY_CONTROL_PLANE","CONTROL"]]as const;
export type AgentCard={id:string;name:string;version:string;endpoint:string;skills:string[];domains:string[];permissions:string[];risk:"LOW"|"MEDIUM"|"HIGH"|"CRITICAL";requiresApproval:boolean};
export type Delegation={id:string;fromAgent:string;toAgent:string;objective:string;scope:string[];approvalId:string|null;status:"PROPOSED"|"APPROVED"|"EXECUTING"|"COMPLETED"|"BLOCKED";evidence:string[];createdAt:string};
const c=(v:unknown,n=500)=>String(v??"").trim().slice(0,n),h=(v:unknown)=>createHash("sha256").update(JSON.stringify(v)).digest("hex");
export function buildAgentCard(i:Partial<AgentCard>):AgentCard{const id=c(i.id,80);if(!id)throw new Error("AGENT_ID_REQUIRED");return{id,name:c(i.name,120)||id,version:c(i.version,30)||"1.0.0",endpoint:c(i.endpoint,300),skills:Array.isArray(i.skills)?[...new Set(i.skills.map(x=>c(x,100)))]:[],domains:Array.isArray(i.domains)?[...new Set(i.domains.map(x=>c(x,80)))]:[],permissions:Array.isArray(i.permissions)?[...new Set(i.permissions.map(x=>c(x,80)))]:[],risk:i.risk??"MEDIUM",requiresApproval:i.requiresApproval??true};}
export function discoverAgents(cards:AgentCard[],skill?:string,domain?:string){return cards.filter(a=>(!skill||a.skills.includes(skill))&&(!domain||a.domains.includes(domain))).sort((a,b)=>a.id.localeCompare(b.id));}
export function buildDelegation(i:Partial<Delegation>):Delegation{if(!c(i.fromAgent,80)||!c(i.toAgent,80))throw new Error("AGENT_PARTICIPANTS_REQUIRED");if(!c(i.objective,500))throw new Error("DELEGATION_OBJECTIVE_REQUIRED");const d={id:"dlg_"+h({from:i.fromAgent,to:i.toAgent,objective:i.objective}).slice(0,24),fromAgent:c(i.fromAgent,80),toAgent:c(i.toAgent,80),objective:c(i.objective,500),scope:Array.isArray(i.scope)?i.scope.map(x=>c(x,100)):[],approvalId:i.approvalId?c(i.approvalId,100):null,status:i.approvalId?"APPROVED":"PROPOSED" as Delegation["status"],evidence:[],createdAt:new Date().toISOString()};return d;}
export function delegationGate(d:Delegation,card:AgentCard,approved:boolean){if(d.toAgent!==card.id)return{allowed:false,reason:"AGENT_TARGET_MISMATCH"};if(card.requiresApproval&&!approved)return{allowed:false,reason:"HUMAN_APPROVAL_REQUIRED"};const missing=d.scope.filter(x=>!card.permissions.includes(x));if(missing.length)return{allowed:false,reason:"DELEGATION_SCOPE_DENIED",missing};return{allowed:true,reason:"DELEGATION_ALLOWED"};}
export function authorizeDelegation(d:Delegation,approvalId:string){if(!c(approvalId,100))throw new Error("APPROVAL_ID_REQUIRED");return{...d,approvalId:c(approvalId,100),status:"APPROVED"as const};}
export function addEvidence(d:Delegation,evidence:string[]){return{...d,evidence:[...new Set([...d.evidence,...evidence.map(x=>c(x,300)).filter(Boolean)])].slice(-100)};}
export function verifyDelegatedResult(expected:string,result:unknown){const actual=h(result);return{verified:actual===expected,actual,expected};}
export function reputationScore(successes:number,attempts:number,failures:number){const rate=attempts?successes/attempts:.5;return Math.max(0,Math.min(1,rate*.7+(1-Math.min(1,failures/Math.max(1,attempts)))*.3));}
export function trustScore(card:AgentCard,reputation:number){const riskPenalty=card.risk==="CRITICAL"?.3:card.risk==="HIGH"?.15:card.risk==="MEDIUM"?.05:0;return Math.max(0,reputation-riskPenalty);}
export function classifyDelegationFailure(e:unknown){const m=c(e,300).toUpperCase();if(m.includes("TIMEOUT"))return"TRANSIENT";if(m.includes("SCOPE")||m.includes("AUTH"))return"GOVERNANCE";if(m.includes("VERIFY"))return"VALIDATION";return"UNKNOWN";}
export function retryDelegation(attempt:number,max=3){return{retry:attempt<max,nextAttempt:attempt+1};}
export function mergeAgentPlans(plans:Array<{agentId:string;steps:string[]}>){const steps=[...new Set(plans.flatMap(p=>p.steps.map(x=>c(x,300)).filter(Boolean)))];return{agents:plans.map(p=>p.agentId),steps,integrity:h({steps,agents:plans.map(p=>p.agentId)})};}
export function syncMemory(entries:Array<{key:string;value:unknown;confidence:number}>){const m=new Map<string,{key:string;value:unknown;confidence:number}>();for(const e of entries){const old=m.get(e.key);if(!old||e.confidence>old.confidence)m.set(e.key,e);}return[...m.values()];}
export function versionCompatibility(a:AgentCard,b:AgentCard){return{compatible:a.skills.some(s=>b.skills.includes(s)),versionA:a.version,versionB:b.version};}
export function certifyAgent(card:AgentCard,checks:{identity:boolean;authorization:boolean;evidence:boolean;verification:boolean}){const certified=Object.values(checks).every(Boolean);return{certified,certificate:certified?"uac_"+h({id:card.id,version:card.version}).slice(0,24):null};}
export function controlPlane(i:{card:AgentCard;delegation:Delegation;approved:boolean;reputation:number}){const gate=delegationGate(i.delegation,i.card,i.approved);if(!gate.allowed)return{decision:"BLOCK",...gate};return{decision:"DELEGATE",trust:trustScore(i.card,i.reputation),evidenceRequired:true};}
