import{createHash}from"node:crypto";
export const INTEROP_VERSION="interop-v1" as const;
const clean=(v:unknown,n=500)=>String(v??"").trim().slice(0,n); const sha=(v:unknown)=>createHash("sha256").update(JSON.stringify(v)).digest("hex");
export type McpServer={id:string;url:string;name?:string;protocolVersion?:string;authScope?:string};
export async function mcpJsonRpc(server:McpServer,method:string,params:Record<string,unknown>={},headers:Record<string,string>={}){const body={jsonrpc:"2.0",id:sha({server:server.id,method,params,nonce:Date.now()}).slice(0,16),method,params};const r=await fetch(server.url,{method:"POST",headers:{"content-type":"application/json",...headers},body:JSON.stringify(body),signal:AbortSignal.timeout(30000)});if(!r.ok)throw new Error("MCP_HTTP_"+r.status);const j=await r.json() as any;if(j.error)throw new Error("MCP_RPC_"+String(j.error.message||"ERROR"));return j.result??j;}
export async function mcpInitialize(server:McpServer){return mcpJsonRpc(server,"initialize",{protocolVersion:server.protocolVersion||"2025-06-18",capabilities:{},clientInfo:{name:"core-engine",version:INTEROP_VERSION}})}
export async function mcpListTools(server:McpServer){return mcpJsonRpc(server,"tools/list",{})}
export async function mcpCallTool(server:McpServer,name:string,args:Record<string,unknown>={}){return mcpJsonRpc(server,"tools/call",{name,arguments:args})}
export function verifyInteropResult(result:unknown,expectedDigest?:string){const digest=sha(result);return{verified:!expectedDigest||digest===expectedDigest,digest,expectedDigest:expectedDigest||null}}
export function mcpFailure(e:unknown){const m=clean(e,500);return{recoverable:/TIMEOUT|429|500|502|503|504/i.test(m),reason:m}}
export type AgentCard={id:string;name:string;version:string;url:string;skills:string[];capabilities:string[];authSchemes:string[]};
export type A2ATask={taskId:string;objective:string;agentId:string;status:"SUBMITTED"|"WORKING"|"COMPLETED"|"FAILED";approvalId:string|null;artifacts:unknown[];evidence:string[];createdAt:string;digest:string};
export function buildAgentCard(x:Partial<AgentCard>):AgentCard{const id=clean(x.id,100);if(!id)throw new Error("A2A_AGENT_ID_REQUIRED");return{id,name:clean(x.name,200)||id,version:clean(x.version,50)||"1.0.0",url:clean(x.url,1000),skills:Array.isArray(x.skills)?x.skills.map(v=>clean(v)).filter(Boolean):[],capabilities:Array.isArray(x.capabilities)?x.capabilities.map(v=>clean(v)).filter(Boolean):[],authSchemes:Array.isArray(x.authSchemes)?x.authSchemes.map(v=>clean(v)).filter(Boolean):[]}}
export function buildA2ATask(agentId:string,objective:string,approvalId?:string|null):A2ATask{const base={agentId:clean(agentId,100),objective:clean(objective,1000),approvalId:approvalId?clean(approvalId,200):null};if(!base.agentId||!base.objective)throw new Error("A2A_TASK_FIELDS_REQUIRED");const now=new Date().toISOString();return{taskId:"a2a_"+sha({base,now}).slice(0,24),...base,status:"SUBMITTED",artifacts:[],evidence:[],createdAt:now,digest:sha(base)}}
export function a2aDelegationGate(t:A2ATask,approved:boolean){if(!approved||!t.approvalId)return{allowed:false,reason:"A2A_APPROVAL_REQUIRED"};return{allowed:true,reason:"A2A_DELEGATION_ALLOWED"}}
export async function a2aSend(card:AgentCard,task:A2ATask,headers:Record<string,string>={}){const gate=a2aDelegationGate(task,Boolean(task.approvalId));if(!gate.allowed)throw new Error(gate.reason);const r=await fetch(card.url,{method:"POST",headers:{"content-type":"application/json",...headers},body:JSON.stringify(task),signal:AbortSignal.timeout(30000)});if(!r.ok)throw new Error("A2A_HTTP_"+r.status);return r.json()}
export function verifyA2AResult(result:unknown,expectedDigest?:string){return verifyInteropResult(result,expectedDigest)}
export function interoperabilityRoute(input:{mcp?:McpServer[];agents?:AgentCard[];approved:boolean}){if(!input.approved)return{decision:"BLOCK",reason:"APPROVAL_REQUIRED"};if(input.mcp?.length)return{decision:"MCP",target:input.mcp[0].id};if(input.agents?.length)return{decision:"A2A",target:input.agents[0].id};return{decision:"NO_PROVIDER"}}
