import { buildDecision } from "@/lib/ai-decision";
import { extractJobFeatures, scoreBucket } from "@/lib/job-learning";
export type JobOpportunity={source:string;url:string;title:string;company:string|null;location:string|null;salary:string|null;description:string|null;publishedAt:string|null;raw:Record<string,unknown>};
const sources=[["pracuj.pl","pracuj.pl"],["indeed","indeed.com"],["olx","olx.pl"],["linkedin","linkedin.com/jobs"],["nofluffjobs","nofluffjobs.com"],["justjoin.it","justjoin.it"],["rocketjobs","rocketjobs.pl"],["pracapolis","pracapolis.pl"],["adzuna","adzuna.pl"],["jooble","jooble.org"]];
const queries=["Business Development Manager","Operations Manager","Customer Experience Manager","Customer Service Manager","Sales Manager","Account Manager Key Account Manager","Export Manager Commercial Manager","German speaking manager customer service","Process Manager Team Leader Supervisor"];
function text(x:unknown){return typeof x==="string"?x.trim():""}\nfunction firstMatch(value:string,patterns:RegExp[]){for(const pattern of patterns){const match=value.match(pattern);if(match?.[1])return match[1].trim()}return null}
function normalize(r:Record<string,unknown>,source:string):JobOpportunity|null{const url=text(r.link),title=text(r.title),snippet=text(r.snippet);if(!url||!title)return null;const hay=title+" "+snippet;const location=firstMatch(hay,[/(?:location|lokalizacja|miejsce pracy)\\s*[:|-]\\s*([^|.]+)/i,/(Gliwice|Zabrze|Bytom|Ruda Śląska|Tarnowskie Góry|Knurów)/i]);const salary=firstMatch(hay,[/((?:PLN|zł)\\s*[\\d\\s.,]+(?:[-–]\\s*[\\d\\s.,]+)?(?:\\s*(?:brutto|gross))?)/i,/([\\d\\s.,]+\\s*(?:PLN|zł)(?:\\s*[-–]\\s*[\\d\\s.,]+\\s*(?:PLN|zł))?)/i]);const company=firstMatch(hay,[/(?:company|firma|pracodawca)\\s*[:|-]\\s*([^|.]+)/i,/[-–—]\\s*([A-Z][A-Za-z0-9&. -]{2,60})(?:\\s*\\||$)/]);return{source,url,title,company,location,salary,description:snippet||null,publishedAt:text(r.date)||text(r.datePublished)||null,raw:r}}
async function search(q:string){const key=process.env.SERPER_API_KEY,endpoint=process.env.JOB_SEARCH_API_URL||"https://google.serper.dev/search";if(!key)return[];const r=await fetch(endpoint,{method:"POST",headers:{"X-API-KEY":key,"Content-Type":"application/json"},body:JSON.stringify({q,gl:"pl",hl:"pl",num:10}),cache:"no-store",signal:AbortSignal.timeout(12000)});if(!r.ok)throw new Error("JOB_SEARCH_"+r.status);return((await r.json()) as {organic?:Record<string,unknown>[]}).organic||[]}
export async function discoverJobs(){const out:JobOpportunity[]=[],errors:string[]=[];const targets=sources.map(x=>"site:"+x[1]).join(" OR ");const local="(\\"Gliwice\\" OR \\"Zabrze\\" OR \\"Bytom\\" OR \\"Ruda Śląska\\" OR \\"Tarnowskie Góry\\" OR \\"Knurów\\")";const settled=await Promise.allSettled(queries.map(role=>search("("+role+") "+local+" ("+targets+")")));settled.forEach((result,index)=>{if(result.status==="rejected"){errors.push(queries[index]+":"+String(result.reason));return}for(const row of result.value){const source=sources.find(x=>text(row.link).includes(x[1]))?.[0]||"web",j=normalize(row,source);if(j)out.push(j)}});const dedupe=new Map<string,JobOpportunity>();for(const j of out)dedupe.set(j.url,j);return{jobs:[...dedupe.values()],errors}}
export async function scoreJobs(jobs:JobOpportunity[],learningWeights:Record<string,number>={},featureWeights:Record<string,number>={},interactionWeights:Record<string,number>={}){
 const policy=await buildDecision([{name:"target_roles",value:queries.join(";"),source:"job_agent_policy"},{name:"location_radius",value:"Gliwice + 30 km",source:"job_agent_policy"},{name:"german_level",value:"B2+",source:"candidate_profile"},{name:"english_level",value:"B2+",source:"candidate_profile"},{name:"management_experience",value:"yes",source:"candidate_profile"},{name:"driving_license",value:"none",source:"candidate_constraint"}],"jobs",[]);
 const roleTerms=["business development","operations","customer experience","sales","account manager","key account","export manager","commercial","process manager","team leader","supervisor","customer service"];
 const scored=jobs.map(j=>{const hay=(j.title+" "+(j.description||"")+" "+(j.location||"")).toLowerCase();let score=35;const roleHits=roleTerms.filter(x=>hay.includes(x));score+=Math.min(30,roleHits.length*7);if(hay.includes("german")||hay.includes("deutsch")||hay.includes("niemiecki"))score+=15;if(hay.includes("english")||hay.includes("angielski"))score+=7;if(hay.includes("gliwice"))score+=10;else if(/zabrze|bytom|ruda śląska|knurów|tarnowskie góry/.test(hay))score+=7;if(hay.includes("driving licence")||hay.includes("prawo jazdy"))score-=10;
  const deterministic=Math.max(0,Math.min(100,score)),features=extractJobFeatures({...j,match_score:deterministic}),bucketWeight=learningWeights[scoreBucket(deterministic)]??1;
  const keys=Object.entries(features).map(([k,v])=>k+"="+String(v)),featureAdjustment=Math.max(.75,Math.min(1.25,keys.reduce((p,k)=>p*(featureWeights[k]??1),1)));
  const pairs:string[]=[];for(let i=0;i<keys.length;i++)for(let z=i+1;z<keys.length;z++)pairs.push(keys[i]+" & "+keys[z]);
  const interactionProduct=pairs.reduce((p,k)=>p*(interactionWeights[k]??1),1),interactionAdjustment=Math.max(.85,Math.min(1.15,interactionProduct));
  const calibrated=Math.max(0,Math.min(100,Math.round(deterministic*bucketWeight*featureAdjustment*interactionAdjustment)));
  const applied=bucketWeight!==1||featureAdjustment!==1||interactionAdjustment!==1;
  return {...j,matchScore:calibrated,decision:calibrated>=75?"APPLY_CANDIDATE":calibrated>=60?"REVIEW":"REJECT",decisionReason:applied?policy.recommendation+"; learning policy applied (bucket="+bucketWeight.toFixed(2)+", features="+featureAdjustment.toFixed(2)+", interactions="+interactionAdjustment.toFixed(2)+")":policy.recommendation,applicationMode:calibrated>=75?"REVIEW_BEFORE_SUBMIT":"REVIEW",learning:{policyVersion:"interaction-policy-v1",features,bucketWeight,featureAdjustment,interactionAdjustment}};
 });
 return{policy,scored};
}