import { buildDecision } from "@/lib/ai-decision";
import { extractJobFeatures, scoreBucket } from "@/lib/job-learning";
export type JobOpportunity={source:string;url:string;title:string;company:string|null;location:string|null;salary:string|null;description:string|null;publishedAt:string|null;raw:Record<string,unknown>};
const sources=[["pracuj.pl","site:pracuj.pl/praca"],["indeed","site:pl.indeed.com"],["olx","site:olx.pl/praca"],["linkedin","site:linkedin.com/jobs/view"],["nofluffjobs","site:nofluffjobs.com/job"],["justjoin.it","site:justjoin.it/offers"],["rocketjobs","site:rocketjobs.pl"],["pracapolis","site:pracapolis.pl"],["adzuna","site:adzuna.pl"],["jooble","site:pl.jooble.org"]];
const queries=["Business Development Manager","Operations Manager","Customer Experience Manager","Sales Manager","Account Manager Key Account Manager","Export Manager Commercial Manager","German speaking manager customer service","process manager team leader supervisor"];
function text(x:unknown){return typeof x==="string"?x:""}
function normalize(r:Record<string,unknown>,source:string):JobOpportunity|null{const url=text(r.link),title=text(r.title);if(!url||!title)return null;return{source,url,title,company:null,location:null,salary:null,description:text(r.snippet),publishedAt:null,raw:r}}
async function search(q:string){const key=process.env.SERPER_API_KEY,endpoint=process.env.JOB_SEARCH_API_URL||"https://google.serper.dev/search";if(!key)return[];const r=await fetch(endpoint,{method:"POST",headers:{"X-API-KEY":key,"Content-Type":"application/json"},body:JSON.stringify({q,gl:"pl",hl:"pl",num:10}),cache:"no-store",signal:AbortSignal.timeout(12000)});if(!r.ok)throw new Error("JOB_SEARCH_"+r.status);return((await r.json()) as {organic?:Record<string,unknown>[]}).organic||[]}
export async function discoverJobs(){const out:JobOpportunity[]=[],errors:string[]=[];const targets=sources.map(x=>x[1]+" ("+x[0]+")").join(" OR ");for(const role of queries)try{const rows=await search("("+role+") ("Gliwice" OR "Zabrze" OR "Bytom" OR "Ruda Śląska" OR "Tarnowskie Góry" OR "Knurów") "+targets);for(const row of rows){const source=sources.find(x=>text(row.link).includes(x[1].replace("site:","").split("/")[0]))?.[0]||"web",j=normalize(row,source);if(j)out.push(j)}}catch(e){errors.push(role+":"+String(e))}const dedupe=new Map<string,JobOpportunity>();for(const j of out)dedupe.set(j.url,j);return{jobs:[...dedupe.values()],errors}}
export async function scoreJobs(jobs:JobOpportunity[],learningWeights:Record<string,number>={},featureWeights:Record<string,number>={},interactionWeights:Record<string,number>={}){
 const policy=await buildDecision([{name:"target_roles",value:queries.join(";"),source:"job_agent_policy"},{name:"location_radius",value:"Gliwice + 30 km",source:"job_agent_policy"},{name:"german_level",value:"B2+",source:"candidate_profile"},{name:"english_level",value:"B2+",source:"candidate_profile"},{name:"management_experience",value:"yes",source:"candidate_profile"},{name:"driving_license",value:"none",source:"candidate_constraint"}],"jobs",[]);
 const roleTerms=["business development","operations","customer experience","sales","account manager","key account","export manager","commercial","process manager","team leader","supervisor","customer service"];
 const scored=jobs.map(j=>{const hay=(j.title+" "+(j.description||"")+" "+(j.location||"")).toLowerCase();let score=35;const roleHits=roleTerms.filter(x=>hay.includes(x));score+=Math.min(30,roleHits.length*7);if(hay.includes("german")||hay.includes("deutsch"))score+=15;if(hay.includes("english")||hay.includes("angielski"))score+=7;if(hay.includes("gliwice"))score+=10;else if(/zabrze|bytom|ruda śląska|knurów|tarnowskie góry/.test(hay))score+=7;if(hay.includes("driving licence")||hay.includes("prawo jazdy"))score-=10;
  const deterministic=Math.max(0,Math.min(100,score)),features=extractJobFeatures({...j,match_score:deterministic}),bucketWeight=learningWeights[scoreBucket(deterministic)]??1;
  const keys=Object.entries(features).map(([k,v])=>k+"="+String(v)),featureAdjustment=Math.max(.75,Math.min(1.25,keys.reduce((p,k)=>p*(featureWeights[k]??1),1)));
  const pairs:string[]=[];for(let i=0;i<keys.length;i++)for(let z=i+1;z<keys.length;z++)pairs.push(keys[i]+" & "+keys[z]);
  const interactionProduct=pairs.reduce((p,k)=>p*(interactionWeights[k]??1),1),interactionAdjustment=Math.max(.85,Math.min(1.15,interactionProduct));
  const calibrated=Math.max(0,Math.min(100,Math.round(deterministic*bucketWeight*featureAdjustment*interactionAdjustment)));
  const applied=bucketWeight!==1||featureAdjustment!==1||interactionAdjustment!==1;
  return {...j,matchScore:calibrated,decision:calibrated>=75?"APPLY_CANDIDATE":calibrated>=60?"REVIEW":"REJECT",decisionReason:applied?policy.recommendation+"; learning policy applied (bucket="+bucketWeight.toFixed(2)+", features="+featureAdjustment.toFixed(2)+", interactions="+interactionAdjustment.toFixed(2)+")":policy.recommendation,applicationMode:calibrated>=75?"REVIEW_BEFORE_SUBMIT":"REVIEW",learning:{policyVersion:"interaction-policy-v1",features,bucketWeight,featureAdjustment,interactionAdjustment}};
 });
 return{policy,scored};
}