import type { CoreEngineDomain } from "@/lib/m25-01-domain-router";

export type DomainPolicy = {
  domain: CoreEngineDomain;
  objective: string;
  requiredInputs: string[];
  preferredMethods: string[];
  requiredMetrics: string[];
  scenarioTypes: string[];
  riskRules: string[];
  confidenceRules: string[];
  outputSections: string[];
};

const policies: Record<CoreEngineDomain, DomainPolicy> = {
  EQUITY:{domain:"EQUITY",objective:"Ocena jakości biznesu, wyceny, katalizatorów i ryzyka.",requiredInputs:["ticker/company","financial statements","valuation inputs","market price"],preferredMethods:["DCF","multiples","quality of earnings","competitive moat","capital allocation","multi-timeframe technical context"],requiredMetrics:["revenue growth","EBITDA margin","FCF","ROIC","net debt","P/E or EV/EBITDA"],scenarioTypes:["BASE","UPSIDE","DOWNSIDE"],riskRules:["No buy/sell conclusion without assumptions and disclaimer","Flag stale or estimated financial data"],confidenceRules:["Separate observed facts from estimates","Use ranges for valuation"],outputSections:["investment thesis","drivers","risks","scenarios","invalidation"]},
  FX_MACRO:{domain:"FX_MACRO",objective:"Ocena reżimu makro, względnej siły walut i asymetrii ryzyka.",requiredInputs:["currency pair/theme","spot price","rates","central-bank context","macro releases"],preferredMethods:["cross-asset analysis","rate differential","positioning","regime detection","volatility targeting"],requiredMetrics:["rate differential","realized volatility","implied volatility when available","positioning","key technical levels"],scenarioTypes:["BASE","BULL","BEAR"],riskRules:["Separate short-term price action from structural view","State trigger and invalidation"],confidenceRules:["Penalize conflicting cross-asset signals","Report uncertainty"],outputSections:["macro context","positioning","levels","trigger","invalidation","position management"]},
  SPORTS_BETTING:{domain:"SPORTS_BETTING",objective:"Identyfikacja dodatniej wartości oczekiwanej przy kontroli wariancji.",requiredInputs:["event","market","odds","model inputs","line timestamp"],preferredMethods:["Poisson","Dixon-Coles","Elo","xG","player props","line movement"],requiredMetrics:["model probability","implied probability","edge","EV","fractional Kelly"],scenarioTypes:["MODEL_BASE","MODEL_DOWN","MODEL_UP"],riskRules:["Never call a bet certain","Require bankroll and variance disclosure","Flag stale odds"],confidenceRules:["Probability must be model-derived or sourced","Reduce confidence when key lineup/injury data is missing"],outputSections:["probability vs odds","edge","market","stake","risks"]},
  REAL_ESTATE:{domain:"REAL_ESTATE",objective:"Ocena cash flow, ryzyka lokalizacji, finansowania i wyjścia.",requiredInputs:["purchase price","rent","opex","vacancy","capex","financing","location"],preferredMethods:["NOI","Cap Rate","Cash-on-Cash","IRR","Equity Multiple","sensitivity analysis"],requiredMetrics:["NOI","cap rate","cash-on-cash","DSCR when debt exists","IRR","vacancy"],scenarioTypes:["BASE","UPSIDE","DOWNSIDE"],riskRules:["Use conservative vacancy, opex and capex","Stress rates and rents"],confidenceRules:["Separate asking price from transaction evidence","Flag missing local comparables"],outputSections:["thesis","metrics","scenarios","risks","mitigations","exit"]},
  BUSINESS:{domain:"BUSINESS",objective:"Budowa realistycznej strategii wzrostu z ochroną downside.",requiredInputs:["problem","customer","market","pricing","costs","distribution","competition"],preferredMethods:["TAM/SAM/SOM","unit economics","GTM","competitive analysis","sensitivity analysis"],requiredMetrics:["CAC","LTV","gross margin","payback","retention","revenue"],scenarioTypes:["BASE","UPSIDE","DOWNSIDE"],riskRules:["Every material number needs source or assumption","Avoid vanity metrics"],confidenceRules:["Mark assumptions explicitly","Use sensitivity ranges"],outputSections:["problem & solution","market","business model","GTM","competition","financials","team risks","funding"]},
  FORECASTING:{domain:"FORECASTING",objective:"Tworzenie kalibrowanych prognoz z jawną niepewnością.",requiredInputs:["forecast question","horizon","base rate","historical reference class","current signals"],preferredMethods:["base rates","reference class forecasting","Bayesian updating","scenario planning","decision trees","causal inference"],requiredMetrics:["probability","range","confidence","leading indicators"],scenarioTypes:["BASE","UPSIDE","DOWNSIDE"],riskRules:["No false precision","Distinguish prediction from projection"],confidenceRules:["State confidence interval or range","List invalidation conditions"],outputSections:["decision question","base rate","signals","scenarios","leading indicators"]},
  MARKET_NICHES:{domain:"MARKET_NICHES",objective:"Wykrywanie monetizable structural trends poza AI.",requiredInputs:["theme","geography","customer pain","market evidence","competitive landscape"],preferredMethods:["structural tailwinds","bottleneck analysis","barrier analysis","timing","value-chain mapping"],requiredMetrics:["market growth","monetization evidence","barriers","timing","cash-flow potential"],scenarioTypes:["EARLY","SWEET_SPOT","LATE"],riskRules:["Reject hype without monetization evidence","Identify who loses if theme wins"],confidenceRules:["Require multiple independent signals","Flag weak evidence"],outputSections:["why now","pain point","barriers","timing","exposure","examples"]},
};

export function getDomainPolicy(domain: CoreEngineDomain): DomainPolicy { return policies[domain]; }
export function getDomainPolicies(domains: readonly CoreEngineDomain[]): DomainPolicy[] { return domains.map(getDomainPolicy); }
