import type { CapabilityAdapter, CapabilityAdapterContext, CapabilityAdapterReceipt } from "@/lib/capability-adapters";
import type { CapabilityAction } from "@/lib/capability-contracts";

type Json = Record<string, unknown>;

function requiredEnv(name: string) {
  const value = process.env[name]?.trim();
  if (!value) throw new Error(name + "_NOT_CONFIGURED");
  return value;
}

async function githubRequest(path: string, init: RequestInit = {}) {
  const token = requiredEnv("CORE_ENGINE_GITHUB_TOKEN");
  const response = await fetch("https://api.github.com" + path, {
    ...init,
    headers: {
      Accept: "application/vnd.github+json",
      Authorization: "Bearer " + token,
      "X-GitHub-Api-Version": "2026-03-10",
      "User-Agent": "Core-Engine-Agent/1.0",
      ...(init.headers ?? {})
    },
    cache: "no-store"
  });
  const text = await response.text();
  let body: Json = {};
  try { body = text ? JSON.parse(text) : {}; } catch {}
  if (!response.ok) throw new Error("GITHUB_HTTP_" + response.status + ":" + String(body.message ?? text).slice(0, 300));
  return body;
}

async function vercelRequest(path: string, init: RequestInit = {}) {
  const token = requiredEnv("CORE_ENGINE_VERCEL_TOKEN");
  const teamId = process.env.CORE_ENGINE_VERCEL_TEAM_ID?.trim();
  const separator = path.includes("?") ? "&" : "?";
  const url = "https://api.vercel.com" + path + (teamId ? separator + "teamId=" + encodeURIComponent(teamId) : "");
  const response = await fetch(url, {
    ...init,
    headers: {
      Authorization: "Bearer " + token,
      "Content-Type": "application/json",
      ...(init.headers ?? {})
    },
    cache: "no-store"
  });
  const text = await response.text();
  let body: Json = {};
  try { body = text ? JSON.parse(text) : {}; } catch {}
  if (!response.ok) throw new Error("VERCEL_HTTP_" + response.status + ":" + String(body.error?.message ?? body.message ?? text).slice(0, 300));
  return body;
}

function receipt(startedAt: string, message: string, output: Json, sideEffect = true): CapabilityAdapterReceipt {
  return { status: "EXECUTED", startedAt, completedAt: new Date().toISOString(), sideEffect, message, output };
}

function inputString(input: Json, key: string, fallback = "") {
  return typeof input[key] === "string" ? String(input[key]).trim() : fallback;
}

function filesInput(input: Json) {
  const raw = Array.isArray(input.files) ? input.files : [];
  return raw.slice(0, 100).map((item) => {
    const value = item as Json;
    return { path: inputString(value, "path"), content: inputString(value, "content") };
  }).filter((item) => item.path && !item.path.startsWith("/") && !item.path.includes(".."));
}

const githubAdapter: CapabilityAdapter = {
  id: "provider.github.v1",
  supports: (action) => action.id === "github.repository.create" || action.id === "github.repository.commit",
  async execute(action, context) {
    const startedAt = new Date().toISOString();
    const input = context.input ?? {};
    const repo = inputString(input, "repository");
    const owner = inputString(input, "owner") || process.env.CORE_ENGINE_GITHUB_OWNER?.trim() || "";
    const name = inputString(input, "name") || (repo.includes("/") ? repo.split("/").pop() : "");
    if (!owner && !repo.includes("/")) throw new Error("GITHUB_OWNER_REQUIRED");
    if (!name) throw new Error("GITHUB_REPOSITORY_NAME_REQUIRED");

    if (action.id === "github.repository.create") {
      const description = inputString(input, "description", "Generated by Core Engine AI");
      const isPrivate = input.private === true;
      const created = await githubRequest("/user/repos", {
        method: "POST",
        body: JSON.stringify({ name, description, private: isPrivate, auto_init: true })
      });
      const fullName = String(created.full_name ?? (owner + "/" + name));
      const files = filesInput(input);
      const commits: string[] = [];
      for (const file of files) {
        const result = await githubRequest("/repos/" + fullName + "/contents/" + file.path.split("/").map(encodeURIComponent).join("/"), {
          method: "PUT",
          body: JSON.stringify({ message: "feat(agent): add " + file.path, content: Buffer.from(file.content, "utf8").toString("base64"), branch: "main" })
        });
        commits.push(String(result.commit?.sha ?? ""));
      }
      return receipt(startedAt, "GitHub repository created and initialized.", {
        provider: "github", repository: fullName, url: String(created.html_url ?? ""), branch: "main", commits
      });
    }

    const fullName = repo.includes("/") ? repo : owner + "/" + repo;
    const branch = inputString(input, "branch", "main");
    const path = inputString(input, "path");
    const content = inputString(input, "content");
    if (!path || path.includes("..") || path.startsWith("/")) throw new Error("GITHUB_FILE_PATH_INVALID");
    if (!content) throw new Error("GITHUB_FILE_CONTENT_REQUIRED");
    let sha: string | undefined;
    try {
      const existing = await githubRequest("/repos/" + fullName + "/contents/" + path.split("/").map(encodeURIComponent).join("/") + "?ref=" + encodeURIComponent(branch));
      sha = typeof existing.sha === "string" ? existing.sha : undefined;
    } catch {}
    const body: Json = { message: inputString(input, "message", "feat(agent): update " + path), content: Buffer.from(content, "utf8").toString("base64"), branch };
    if (sha) body.sha = sha;
    const result = await githubRequest("/repos/" + fullName + "/contents/" + path.split("/").map(encodeURIComponent).join("/"), { method: "PUT", body: JSON.stringify(body) });
    return receipt(startedAt, "GitHub repository file committed.", { provider: "github", repository: fullName, path, branch, commitSha: String(result.commit?.sha ?? "") });
  }
};

const vercelAdapter: CapabilityAdapter = {
  id: "provider.vercel.v1",
  supports: (action) => action.id === "vercel.project.deploy",
  async execute(action, context) {
    const startedAt = new Date().toISOString();
    const input = context.input ?? {};
    const repo = inputString(input, "repository");
    const name = inputString(input, "name") || repo.split("/").pop() || "core-engine-generated";
    const branch = inputString(input, "branch", "main");
    if (!repo.includes("/")) throw new Error("VERCEL_GITHUB_REPOSITORY_REQUIRED");

    let project: Json;
    try {
      project = await vercelRequest("/v9/projects/" + encodeURIComponent(name));
    } catch {
      project = await vercelRequest("/v9/projects", {
        method: "POST",
        body: JSON.stringify({
          name,
          gitRepository: { type: "github", repo },
          framework: inputString(input, "framework", "nextjs")
        })
      });
    }

    const deployment = await vercelRequest("/v13/deployments", {
      method: "POST",
      body: JSON.stringify({
        name,
        project: String(project.id ?? name),
        target: inputString(input, "target", "production"),
        gitSource: { type: "github", repo, ref: branch }
      })
    });

    return receipt(startedAt, "Vercel deployment requested from GitHub.", {
      provider: "vercel",
      projectId: String(project.id ?? ""),
      projectName: name,
      deploymentId: String(deployment.id ?? ""),
      deploymentUrl: String(deployment.url ?? ""),
      state: String(deployment.readyState ?? deployment.state ?? "QUEUED")
    });
  }
};

export const providerAdapters: CapabilityAdapter[] = [githubAdapter, vercelAdapter];

export function providerReadiness() {
  return {
    github: { configured: Boolean(process.env.CORE_ENGINE_GITHUB_TOKEN?.trim()), ownerConfigured: Boolean(process.env.CORE_ENGINE_GITHUB_OWNER?.trim()) },
    vercel: { configured: Boolean(process.env.CORE_ENGINE_VERCEL_TOKEN?.trim()), teamConfigured: Boolean(process.env.CORE_ENGINE_VERCEL_TEAM_ID?.trim()) }
  };
}
