import{createHash}from"node:crypto";
export const UNIVERSAL_AGENT_OS_VERSION="uaos-v1" as const;
export const UAOS_STAGES=[[301,"UNIVERSAL_AGENT_OS_OBJECTIVE_LAYER","OS"],[302,"UNIVERSAL_AGENT_OS_WORLD_MODEL","OS"],[303,"UNIVERSAL_AGENT_OS_SKILL_LAYER","OS"],[304,"UNIVERSAL_AGENT_OS_TOOL_LAYER","OS"],[305,"UNIVERSAL_AGENT_OS_AGENT_LAYER","OS"],[306,"UNIVERSAL_AGENT_OS_EXECUTION_GRAPH","OS"],[307,"UNIVERSAL_AGENT_OS_POLICY_LAYER","OS"],[308,"UNIVERSAL_AGENT_OS_APPROVAL_LAYER","OS"],[309,"UNIVERSAL_AGENT_OS_EXECUTION_MESH","OS"],[310,"UNIVERSAL_AGENT_OS_EVIDENCE_LAYER","OS"],[311,"UNIVERSAL_AGENT_OS_VERIFICATION_LAYER","OS"],[312,"UNIVERSAL_AGENT_OS_OUTCOME_LAYER","OS"],[313,"UNIVERSAL_AGENT_OS_LEARNING_LAYER","OS"],[314,"UNIVERSAL_AGENT_OS_MEMORY_LAYER","OS"],[315,"UNIVERSAL_AGENT_OS_REPLANNING_LAYER","OS"],[316,"UNIVERSAL_AGENT_OS_RECOVERY_LAYER","OS"],[317,"UNIVERSAL_AGENT_OS_INTEROPERABILITY_LAYER","OS"],[318,"UNIVERSAL_AGENT_OS_REGISTRY_LAYER","OS"],[319,"UNIVERSAL_AGENT_OS_IDENTITY_LAYER","SECURITY"],[320,"UNIVERSAL_AGENT_OS_CREDENTIAL_LAYER","SECURITY"],[321,"UNIVERSAL_AGENT_OS_DATA_GOVERNANCE","GOVERNANCE"],[322,"UNIVERSAL_AGENT_OS_BUDGET_GOVERNANCE","GOVERNANCE"],[323,"UNIVERSAL_AGENT_OS_RISK_GOVERNANCE","GOVERNANCE"],[324,"UNIVERSAL_AGENT_OS_TRUST_GOVERNANCE","GOVERNANCE"],[325,"UNIVERSAL_AGENT_OS_CERTIFICATION","CERTIFICATION"],[326,"UNIVERSAL_AGENT_OS_STATE_MACHINE","RUNTIME"],[327,"UNIVERSAL_AGENT_OS_DURABLE_LEDGER","PERSISTENCE"],[328,"UNIVERSAL_AGENT_OS_EVENT_BUS","RUNTIME"],[329,"UNIVERSAL_AGENT_OS_SCHEDULER","ORCHESTRATION"],[330,"UNIVERSAL_AGENT_OS_SUPERVISOR","CONTROL"],[331,"UNIVERSAL_AGENT_OS_SELF_DIAGNOSTICS","OBSERVABILITY"],[332,"UNIVERSAL_AGENT_OS_SELF_HEALING","RECOVERY"],[333,"UNIVERSAL_AGENT_OS_SELF_EVALUATION","EVALUATION"],[334,"UNIVERSAL_AGENT_OS_SELF_IMPROVEMENT","LEARNING"],[335,"UNIVERSAL_AGENT_OS_SKILL_EVOLUTION","LEARNING"],[336,"UNIVERSAL_AGENT_OS_POLICY_EVOLUTION","GOVERNANCE"],[337,"UNIVERSAL_AGENT_OS_PROVIDER_EVOLUTION","PROVIDER"],[338,"UNIVERSAL_AGENT_OS_CAPABILITY_EVOLUTION","CAPABILITY"],[339,"UNIVERSAL_AGENT_OS_MEMORY_RECONCILIATION","MEMORY"],[340,"UNIVERSAL_AGENT_OS_KNOWLEDGE_RECONCILIATION","MEMORY"],[341,"UNIVERSAL_AGENT_OS_HUMAN_FEEDBACK","LEARNING"],[342,"UNIVERSAL_AGENT_OS_HUMAN_CONTROL","CONTROL"],[343,"UNIVERSAL_AGENT_OS_AUDIT_LINEAGE","AUDIT"],[344,"UNIVERSAL_AGENT_OS_REPLAY_INTEGRITY","INTEGRITY"],[345,"UNIVERSAL_AGENT_OS_TERMINAL_PROOF","CERTIFICATION"],[346,"UNIVERSAL_AGENT_OS_PRODUCTION_READINESS","READINESS"],[347,"UNIVERSAL_AGENT_OS_BUSINESS_OS_BRIDGE","INTEGRATION"],[348,"UNIVERSAL_AGENT_OS_MULTI_TENANT_BOUNDARY","SECURITY"],[349,"UNIVERSAL_AGENT_OS_SAAS_CONTROL_PLANE","CONTROL"],[350,"UNIVERSAL_AGENT_OS_END_TO_END_CERTIFICATION","CERTIFICATION"]] as const;
export type OSState="INTENT"|"PLANNED"|"AWAITING_APPROVAL"|"EXECUTING"|"VERIFYING"|"MEASURING"|"LEARNING"|"RECOVERING"|"COMPLETED"|"BLOCKED";
export type OSRun={runId:string;objective:string;state:OSState;approvalId:string|null;approvalCertificate:string|null;skillIds:string[];toolIds:string[];agentIds:string[];evidence:string[];outcome:string|null;createdAt:string;updatedAt:string;digest:string};
const c=(v:unknown,n=500)=>String(v??"").trim().slice(0,n);const h=(v:unknown)=>createHash("sha256").update(JSON.stringify(v)).digest("hex");
export function createOSRun(objective:string):OSRun{const now=new Date().toISOString(),base={objective:c(objective)||"Continue safely.",state:"INTENT" as OSState};return{runId:"os_"+h({base,now}).slice(0,24),...base,approvalId:null,approvalCertificate:null,skillIds:[],toolIds:[],agentIds:[],evidence:[],outcome:null,createdAt:now,updatedAt:now,digest:h(base)}}
export function transitionOS(r:OSRun,next:OSState){const allowed:Record<OSState,OSState[]>={INTENT:["PLANNED","BLOCKED"],PLANNED:["AWAITING_APPROVAL","BLOCKED"],AWAITING_APPROVAL:["EXECUTING","BLOCKED"],EXECUTING:["VERIFYING","RECOVERING","BLOCKED"],VERIFYING:["MEASURING","RECOVERING","BLOCKED"],MEASURING:["LEARNING","COMPLETED","RECOVERING"],LEARNING:["PLANNED","COMPLETED","RECOVERING"],RECOVERING:["AWAITING_APPROVAL","BLOCKED"],COMPLETED:[],BLOCKED:[]};if(!allowed[r.state].includes(next))throw new Error("OS_INVALID_TRANSITION:"+r.state+"->"+next);if(next==="EXECUTING"&&!r.approvalId)throw new Error("OS_APPROVAL_REQUIRED");if(next==="EXECUTING"&&!r.approvalCertificate)throw new Error("OS_GATE_CERTIFICATION_REQUIRED");const now=new Date().toISOString(),x={...r,state:next,updatedAt:now};return{...x,digest:h({...x,digest:undefined})}}
export function attachApproval(r:OSRun,approvalId:string){if(!c(approvalId,200))throw new Error("OS_APPROVAL_ID_REQUIRED");if(r.state!=="AWAITING_APPROVAL")throw new Error("OS_NOT_AWAITING_APPROVAL");return{...r,approvalId:c(approvalId,200),updatedAt:new Date().toISOString()}}
export function certifyApprovalGate(r:OSRun,missionState:string){if(r.state!=="AWAITING_APPROVAL")throw new Error("OS_GATE_STATE_INVALID");if(!r.approvalId)throw new Error("OS_APPROVAL_REQUIRED");if(String(missionState)!=="APPROVED")throw new Error("MISSION_APPROVAL_REQUIRED");const certificate="uaosgc_"+h({runId:r.runId,approvalId:r.approvalId,missionState,objective:r.objective}).slice(0,24);return{...r,approvalCertificate:certificate,updatedAt:new Date().toISOString()}}
export function addEvidence(r:OSRun,evidence:string){return{...r,evidence:[...r.evidence,c(evidence,300)].filter(Boolean).slice(-100),updatedAt:new Date().toISOString()}}
export function setOutcome(r:OSRun,outcome:string){if(r.state!=="MEASURING"&&r.state!=="LEARNING")throw new Error("OS_OUTCOME_STATE_INVALID");return{...r,outcome:c(outcome,1000),updatedAt:new Date().toISOString()}}
export function recoverOS(r:OSRun){if(r.state!=="RECOVERING")throw new Error("OS_NOT_RECOVERING");return{...r,state:"AWAITING_APPROVAL" as OSState,approvalId:null,updatedAt:new Date().toISOString()}}
export function verifyOS(r:OSRun){return{verified:r.state==="VERIFYING"&&r.evidence.length>0,runDigest:r.digest,state:r.state,evidenceCount:r.evidence.length}}
export function certifyOS(r:OSRun){const verified=verifyOS(r);return{certified:verified.verified&&r.state==="COMPLETED",certificate:verified.verified&&r.state==="COMPLETED"?"uaosc_"+h(r).slice(0,24):null}}
export function osControlPlane(r:OSRun){if(r.state==="INTENT")return{decision:"PLAN"};if(r.state==="PLANNED")return{decision:"REQUEST_APPROVAL"};if(r.state==="AWAITING_APPROVAL")return{decision:"WAIT_APPROVAL"};if(r.state==="RECOVERING")return{decision:"REAPPROVE"};if(r.state==="COMPLETED")return{decision:"CERTIFY"};return{decision:"CONTINUE",state:r.state}}
