import{createHash}from"node:crypto";
export const UNIVERSAL_LEARNING_VERSION="ul-v1" as const;
export const LEARNING_STAGES=[[251,"LEARNING_DATA_CONTRACT","LEARNING"],[252,"OUTCOME_FEATURE_EXTRACTION","LEARNING"],[253,"HUMAN_FEEDBACK_INGESTION","LEARNING"],[254,"SKILL_FEEDBACK_WEIGHTING","LEARNING"],[255,"PROVIDER_FEEDBACK_WEIGHTING","LEARNING"],[256,"OBJECTIVE_CONTEXT_OUTCOME_MODEL","LEARNING"],[257,"COST_LATENCY_FAILURE_FEATURES","LEARNING"],[258,"EVIDENCE_QUALITY_SCORING","EVALUATION"],[259,"LEARNING_EXPERIMENT_ENGINE","EVALUATION"],[260,"CONTROLLED_SKILL_EXPERIMENTS","EVALUATION"],[261,"CONSTRAINED_BANDIT_OPTIMIZER","OPTIMIZATION"],[262,"CONTEXTUAL_SELECTION_POLICY","OPTIMIZATION"],[263,"FEEDBACK_CALIBRATION_ENGINE","CALIBRATION"],[264,"PREDICTION_CALIBRATION","CALIBRATION"],[265,"DRIFT_DETECTION_ENGINE","QUALITY"],[266,"LEARNING_SAFETY_GATE","GOVERNANCE"],[267,"LEARNING_ROLLBACK_ENGINE","RECOVERY"],[268,"MODEL_VERSION_LINEAGE","LIFECYCLE"],[269,"EVALUATION_DATASET_REGISTRY","EVALUATION"],[270,"BENCHMARK_HARNESS","EVALUATION"],[271,"AGENT_EVALUATION_SUITE","EVALUATION"],[272,"SKILL_EVALUATION_SUITE","EVALUATION"],[273,"PROVIDER_EVALUATION_SUITE","EVALUATION"],[274,"LEARNING_CERTIFICATION","CERTIFICATION"],[275,"UNIVERSAL_LEARNING_CONTROL_PLANE","CONTROL"],[276,"SKILL_QUALITY_SCORE","ECONOMY"],[277,"SKILL_SUCCESS_RATE_INDEX","ECONOMY"],[278,"SKILL_COST_INDEX","ECONOMY"],[279,"SKILL_RISK_INDEX","ECONOMY"],[280,"SKILL_LATENCY_INDEX","ECONOMY"],[281,"SKILL_REPUTATION_INDEX","ECONOMY"],[282,"SKILL_CERTIFICATION_INDEX","ECONOMY"],[283,"SKILL_PARETO_FRONTIER","OPTIMIZATION"],[284,"MULTI_OPTION_SKILL_RANKING","OPTIMIZATION"],[285,"BUDGET_ALLOCATION_ENGINE","OPTIMIZATION"],[286,"PROVIDER_PRICING_MODEL","ECONOMY"],[287,"PROVIDER_SLA_ENGINE","ECONOMY"],[288,"SKILL_MARKET_REGISTRY","REGISTRY"],[289,"MARKET_TRUST_ENGINE","TRUST"],[290,"SKILL_REPUTATION_ENGINE","TRUST"],[291,"INCENTIVE_POLICY_ENGINE","GOVERNANCE"],[292,"SKILL_PORTFOLIO_OPTIMIZER","OPTIMIZATION"],[293,"AUTOMATIC_SKILL_ROUTING","ROUTING"],[294,"CONSTRAINED_ECONOMIC_OPTIMIZER","OPTIMIZATION"],[295,"QUALITY_COST_RISK_BALANCER","OPTIMIZATION"],[296,"SKILL_SLA_NEGOTIATION","COORDINATION"],[297,"SKILL_MARKET_FALLBACK","RECOVERY"],[298,"SKILL_ECONOMY_CERTIFICATION","CERTIFICATION"],[299,"UNIVERSAL_SKILL_ECONOMY_REGISTRY","REGISTRY"],[300,"UNIVERSAL_SKILL_ECONOMY_CONTROL_PLANE","CONTROL"]] as const;
export type Feedback={objective:string;skillId:string;providerId?:string;success:boolean;cost:number;latencyMs:number;failureClass?:string;evidenceQuality:number;humanScore?:number};
export type LearningRecord=Feedback&{id:string;createdAt:string;digest:string};
const clean=(v:unknown,n=300)=>String(v??"").trim().slice(0,n);const digest=(v:unknown)=>createHash("sha256").update(JSON.stringify(v)).digest("hex");
export function buildLearningRecord(f:Feedback):LearningRecord{const x={...f,objective:clean(f.objective,500),skillId:clean(f.skillId,100),providerId:f.providerId?clean(f.providerId,100):undefined,cost:Math.max(0,Number(f.cost||0)),latencyMs:Math.max(0,Number(f.latencyMs||0)),evidenceQuality:Math.max(0,Math.min(1,Number(f.evidenceQuality??0))),humanScore:f.humanScore===undefined?undefined:Math.max(0,Math.min(1,Number(f.humanScore)))};return{...x,id:"lr_"+digest(x).slice(0,24),createdAt:new Date().toISOString(),digest:digest(x)}}
export function outcomeFeatures(r:LearningRecord){return{success:r.success?1:0,cost:r.cost,latencyMs:r.latencyMs,failure:r.failureClass?1:0,evidenceQuality:r.evidenceQuality,humanScore:r.humanScore??.5}}
export function feedbackWeight(r:LearningRecord){return Math.max(.05,Math.min(1,.45*r.evidenceQuality+.35*(r.humanScore??.5)+.2))}
export function aggregateFeedback(records:LearningRecord[]){const n=records.length;if(!n)return{attempts:0,successRate:0,weightedSuccessRate:0,avgCost:0,avgLatencyMs:0};const w=records.reduce((s,r)=>s+feedbackWeight(r),0);return{attempts:n,successRate:records.filter(r=>r.success).length/n,weightedSuccessRate:records.reduce((s,r)=>s+feedbackWeight(r)*(r.success?1:0),0)/w,avgCost:records.reduce((s,r)=>s+r.cost,0)/n,avgLatencyMs:records.reduce((s,r)=>s+r.latencyMs,0)/n}}
export function contextualScore(records:LearningRecord[],objective:string,skillId:string){const q=clean(objective,200).toLowerCase().slice(0,30),xs=records.filter(r=>r.skillId===skillId&&r.objective.toLowerCase().includes(q)),a=aggregateFeedback(xs);return{skillId,objective,score:.55*a.weightedSuccessRate+.2*(1-Math.min(1,a.avgCost/100))+.15*(1-Math.min(1,a.avgLatencyMs/10000))+.1}}
export function chooseByLearning(candidates:string[],scores:Record<string,number>){return candidates.map(id=>({id,score:scores[id]??.5})).sort((a,b)=>b.score-a.score||a.id.localeCompare(b.id))[0]??null}
export function detectDrift(baseline:number[],current:number[],threshold=.15){const avg=(x:number[])=>x.length?x.reduce((a,b)=>a+b,0)/x.length:0,b=avg(baseline),c=avg(current);return{baseline:b,current:c,delta:c-b,drift:Math.abs(c-b)>=threshold}}
export function learningSafetyGate(i:{sampleCount:number;drift:boolean;rollbackRequested?:boolean}){if(i.rollbackRequested)return{allowed:false,reason:"ROLLBACK_REQUESTED"};if(i.sampleCount<3)return{allowed:false,reason:"INSUFFICIENT_EVIDENCE"};if(i.drift)return{allowed:false,reason:"DRIFT_DETECTED"};return{allowed:true,reason:"LEARNING_SAFE"}}
export function rollbackDecision(current:string,previous:string,g:{allowed:boolean}){return g.allowed?{action:"PROMOTE",version:current}:{action:"ROLLBACK",version:previous}}
export function paretoFrontier(items:Array<{id:string;quality:number;cost:number;risk:number;latency:number}>){return items.filter(a=>!items.some(b=>b.id!==a.id&&b.quality>=a.quality&&b.cost<=a.cost&&b.risk<=a.risk&&b.latency<=a.latency&&(b.quality>a.quality||b.cost<a.cost||b.risk<a.risk||b.latency<a.latency)))}
export function qualityScore(x:{successRate:number;evidenceQuality:number;confidence:number;cost:number;risk:number;latencyMs:number}){return Math.max(0,Math.min(1,.4*x.successRate+.25*x.evidenceQuality+.2*x.confidence+.15*(1-Math.min(1,(x.cost/100+x.risk+x.latencyMs/10000)/3))))}
export function economicScore(x:{quality:number;successRate:number;cost:number;risk:number;latencyMs:number;reputation:number;certified:boolean}){return Math.max(0,Math.min(1,.3*x.quality+.2*x.successRate+.15*x.reputation+.15*(x.certified?1:0)+.1*(1-Math.min(1,x.cost/100))+.05*(1-x.risk)+.05*(1-Math.min(1,x.latencyMs/10000))))}
export function rankEconomicOptions<T extends{id:string;quality:number;successRate:number;cost:number;risk:number;latencyMs:number;reputation:number;certified:boolean}>(items:T[]){return items.map(x=>({...x,economicScore:economicScore(x)})).sort((a,b)=>b.economicScore-a.economicScore||a.id.localeCompare(b.id))}
export function allocateBudget(items:Array<{id:string;utility:number;cost:number}>,budget:number){let left=Math.max(0,budget);const selected:typeof items=[];for(const x of[...items].sort((a,b)=>b.utility/Math.max(.001,b.cost)-a.utility/Math.max(.001,a.cost))){if(x.cost<=left){selected.push(x);left-=x.cost}}return{selected,remainingBudget:left}}
export function marketTrust(successRate:number,certified:boolean,evidenceQuality:number){return Math.max(0,Math.min(1,.5*successRate+.3*evidenceQuality+.2*(certified?1:0)))}
export function economyControlPlane(items:Array<{id:string;quality:number;successRate:number;cost:number;risk:number;latencyMs:number;reputation:number;certified:boolean}>,budget=Infinity){const ranked=rankEconomicOptions(items),best=ranked[0];if(!best)return{decision:"BLOCK",reason:"NO_OPTIONS"};if(best.cost>budget)return{decision:"BLOCK",reason:"BUDGET_EXCEEDED"};return{decision:"SELECT",id:best.id,score:best.economicScore,cost:best.cost}}
