import { createHash } from "node:crypto";
export const UNIVERSAL_AGENT_OS_V2="uaos-v2" as const;
export const UAOS_V2_STAGES=Array.from({length:50},(_,i)=>({id:301+i,name:"UAOS_V2_STAGE_"+(301+i),phase:i<5?"GOAL":i<12?"PLAN":i<20?"EXECUTION":i<27?"VERIFICATION":i<35?"LEARNING":i<42?"ADAPTATION":i<47?"IMPROVEMENT":"CONTROL"}));
export type UniversalMission={missionId:string;objective:string;status:"PLANNED"|"AWAITING_APPROVAL"|"EXECUTING"|"VERIFYING"|"LEARNING"|"REPLANNING"|"COMPLETED"|"BLOCKED";goal:string;world:string[];skills:string[];agents:string[];tools:string[];approvalId?:string;revision:number;executionPermission:boolean;integrity:string;updatedAt:string};
const now=()=>new Date().toISOString();const sha=(x:unknown)=>createHash("sha256").update(JSON.stringify(x)).digest("hex");
export function createUniversalMission(objective:string,input?:Partial<UniversalMission>):UniversalMission{const goal=objective.trim().slice(0,1000);if(!goal)throw new Error("OBJECTIVE_REQUIRED");const base={missionId:"mis_"+sha({goal,at:now()}).slice(0,24),objective:goal,status:"PLANNED" as const,goal,world:input?.world||[],skills:input?.skills||[],agents:input?.agents||[],tools:input?.tools||[],revision:1,executionPermission:false,updatedAt:now()};return{...base,integrity:sha(base)};}
export function approveUniversalMission(m:UniversalMission,approvalId:string){if(!approvalId.trim())throw new Error("APPROVAL_ID_REQUIRED");const next={...m,status:"EXECUTING" as const,approvalId:approvalId.trim(),executionPermission:true,revision:m.revision+1,updatedAt:now()};return{...next,integrity:sha(next)};}
export function recordMissionOutcome(m:UniversalMission,success:number,evidence:string[]){const status=success>=.8?"COMPLETED":"LEARNING";const next={...m,status:status as UniversalMission["status"],executionPermission:false,revision:m.revision+1,updatedAt:now()};return{...next,integrity:sha({previous:m.integrity,success,evidence,next})};}
export function requestReplan(m:UniversalMission,reason:string){const next={...m,status:"REPLANNING" as const,executionPermission:false,revision:m.revision+1,updatedAt:now()};return{...next,integrity:sha({previous:m.integrity,reason,next})};}
export function verifyMission(m:UniversalMission){return{integrityPresent:Boolean(m.integrity),approvalIntact:Boolean(m.approvalId),executionPermission:m.executionPermission,revision:m.revision};}
export function selfImprovementGate(input:{proposal:string;evidence:number;benefit:number;risk:number;approved:boolean}){const allowed=input.approved&&input.evidence>=3&&input.benefit>input.risk;return{allowed,reason:allowed?"ROLLOUT_ALLOWED":!input.approved?"APPROVAL_REQUIRED":input.evidence<3?"EVIDENCE_INSUFFICIENT":"RISK_EXCEEDS_BENEFIT"};}
