import { createHash } from "node:crypto";
export const UNIVERSAL_TOOL_RUNTIME_VERSION="utr-v1" as const;
export const UTR_STAGES=[
[201,"TOOL_CONTRACT_ENGINE","CONTRACT"],[202,"MCP_TOOL_ADAPTER","INTEROPERABILITY"],[203,"TOOL_DISCOVERY_REGISTRY","DISCOVERY"],[204,"BROWSER_RESEARCH_SKILL","WEB"],[205,"COMPUTER_USE_SKILL","COMPUTER"],[206,"CODE_EXECUTION_SKILL","CODE"],[207,"SANDBOX_EXECUTION_BOUNDARY","SANDBOX"],[208,"FILE_INTELLIGENCE_SKILL","FILES"],[209,"DATABASE_QUERY_SKILL","DATA"],[210,"API_INTEGRATION_SKILL","API"],[211,"CREDENTIAL_BROKER_BOUNDARY","SECURITY"],[212,"SECRET_SCOPE_ENGINE","SECURITY"],[213,"DATA_CLASSIFICATION_ENGINE","SECURITY"],[214,"TOOL_PERMISSION_GATE","GOVERNANCE"],[215,"TOOL_RISK_ENGINE","GOVERNANCE"],[216,"TOOL_COST_ENGINE","OPTIMIZATION"],[217,"TOOL_PROVIDER_ARBITRATION","PROVIDER"],[218,"TOOL_FALLBACK_GRAPH","RECOVERY"],[219,"TOOL_EXECUTION_EVIDENCE","EVIDENCE"],[220,"TOOL_RESULT_VERIFICATION","VALIDATION"],[221,"TOOL_TIMEOUT_RETRY","RECOVERY"],[222,"TOOL_CIRCUIT_BREAKER","RESILIENCE"],[223,"TOOL_PERFORMANCE_MEMORY","LEARNING"],[224,"TOOL_CERTIFICATION","CERTIFICATION"],[225,"UNIVERSAL_TOOL_CONTROL_PLANE","CONTROL"]
] as const;
export type ToolKind="mcp"|"browser"|"computer"|"code"|"sandbox"|"file"|"database"|"api";
export type ToolContract={id:string;version:string;kind:ToolKind;description:string;permissions:string[];domains:string[];risk:"LOW"|"MEDIUM"|"HIGH"|"CRITICAL";estimatedCost:number;timeoutMs:number;providerIds:string[];requiresApproval:boolean};
const clean=(v:unknown,n=300)=>String(v??"").trim().slice(0,n);const uniq=(v:unknown)=>Array.isArray(v)?[...new Set(v.map(x=>clean(x)).filter(Boolean))].slice(0,50):[];const digest=(v:unknown)=>createHash("sha256").update(JSON.stringify(v)).digest("hex");
export function buildToolContract(input:Partial<ToolContract>):ToolContract{const id=clean(input.id,100);if(!id)throw new Error("TOOL_ID_REQUIRED");const kind=input.kind??"api";const risk=input.risk??"MEDIUM";const requiresApproval=input.requiresApproval??(risk==="HIGH"||risk==="CRITICAL");return{id,version:clean(input.version,30)||"1.0.0",kind,description:clean(input.description,1000),permissions:uniq(input.permissions),domains:uniq(input.domains),risk,estimatedCost:Math.max(0,Number(input.estimatedCost??0)),timeoutMs:Math.max(100,Number(input.timeoutMs??30000)),providerIds:uniq(input.providerIds),requiresApproval};}
export function discoverTools(tools:ToolContract[],kind?:ToolKind,domain?:string){return tools.filter(t=>(!kind||t.kind===kind)&&(!domain||t.domains.includes(domain))).sort((a,b)=>a.id.localeCompare(b.id));}
export function classifyData(value:unknown){const s=JSON.stringify(value??"").toLowerCase();if(/password|secret|token|api[_-]?key/.test(s))return"SECRET";if(/email|phone|address|name/.test(s))return"PII";return"PUBLIC";}
export function permissionGate(tool:ToolContract,requested:string[],approved:boolean){const missing=requested.filter(p=>!tool.permissions.includes(p));if(missing.length)return{allowed:false,reason:"PERMISSION_MISSING",missing};if(tool.requiresApproval&&!approved)return{allowed:false,reason:"HUMAN_APPROVAL_REQUIRED",missing:[]};return{allowed:true,reason:"TOOL_EXECUTION_ALLOWED",missing:[]};}
export function riskScore(tool:ToolContract,context:Record<string,unknown>={}){let score=tool.risk==="CRITICAL"?1:tool.risk==="HIGH"?.75:tool.risk==="MEDIUM"?.45:.2;if(context.dataClass==="SECRET")score=Math.min(1,score+.2);if(tool.kind==="computer")score=Math.min(1,score+.1);return{score,level:score>=.85?"CRITICAL":score>=.65?"HIGH":score>=.35?"MEDIUM":"LOW"} as const;}
export function costEstimate(tool:ToolContract,invocations=1){const n=Math.max(1,Math.floor(invocations));return{cost:tool.estimatedCost*n,timeoutMs:tool.timeoutMs*n};}
export function providerArbitration(tools:ToolContract[],available:string[]){const candidates=tools.filter(t=>t.providerIds.some(p=>available.includes(p)));if(!candidates.length)throw new Error("NO_TOOL_PROVIDER");return candidates.sort((a,b)=>a.estimatedCost-b.estimatedCost||a.id.localeCompare(b.id))[0];}
export function fallbackGraph(tools:ToolContract[]){return Object.fromEntries(tools.map(t=>[t.id,tools.filter(x=>x.id!==t.id&&x.kind===t.kind).slice(0,3).map(x=>x.id)]));}
export function buildExecutionEvidence(tool:ToolContract,input:unknown,output:unknown){return{toolId:tool.id,version:tool.version,inputDigest:digest(input),outputDigest:digest(output),contractDigest:digest(tool),createdAt:new Date().toISOString()};}
export function verifyToolResult(expectedHash:string,output:unknown){return{verified:digest(output)===expectedHash,actualDigest:digest(output),expectedHash};}
export function retryDecision(attempt:number,maxAttempts=3,errorCode="TIMEOUT"){return{retry:attempt<maxAttempts,attempt:attempt+1,reason:attempt<maxAttempts?errorCode:"RETRY_EXHAUSTED"};}
export function circuitState(failures:number,threshold=5){return{open:failures>=threshold,failures,threshold};}
export function toolPerformance(successes:number,attempts:number,cost:number,latencyMs:number){return{successRate:attempts?successes/attempts:0,avgCost:attempts?cost/attempts:0,avgLatencyMs:attempts?latencyMs/attempts:0};}
export function certifyTool(tool:ToolContract,checks:{contract:boolean;permission:boolean;provider:boolean;evidence:boolean}){const certified=checks.contract&&checks.permission&&checks.provider&&checks.evidence;return{certified,certificate:certified?"utc_"+digest({id:tool.id,version:tool.version,checks}).slice(0,24):null};}
export function controlPlane(input:{tool:ToolContract;requestedPermissions:string[];approved:boolean;availableProviders:string[];dataClass?:string}){const gate=permissionGate(input.tool,input.requestedPermissions,input.approved);if(!gate.allowed)return{decision:"BLOCK",...gate};const risk=riskScore(input.tool,{dataClass:input.dataClass});if(risk.level==="CRITICAL"&&!input.approved)return{decision:"BLOCK",reason:"CRITICAL_APPROVAL_REQUIRED"};return{decision:"ALLOW",risk,provider:input.availableProviders.find(p=>input.tool.providerIds.includes(p))??null,evidenceRequired:true};}
