import {createHash} from "node:crypto";
import {promises as fs} from "node:fs";
import path from "node:path";
import {registerSkillAdapter} from "./registry";
import type {AdapterExecutionContext,AdapterResult,SkillAction,SkillPermission} from "./contracts";
function safeRelative(root:string,candidate:string){if(!candidate||path.isAbsolute(candidate))throw new Error("WORKSPACE_PATH_MUST_BE_RELATIVE");const base=path.resolve(root);const resolved=path.resolve(base,candidate);if(resolved!==base&&!resolved.startsWith(base+path.sep))throw new Error("WORKSPACE_PATH_OUTSIDE_ROOT");return resolved;}
function assertNoSecret(value:string){if(/(^|[._-])(api[_-]?key|secret|token|password|private[_-]?key)([._-]|$)/i.test(path.basename(value)))throw new Error("SECRET_PATH_BLOCKED");}
export const workspaceAdapter={id:"core.workspace.v1",version:"1.0.0",capabilities:["READ_FILE","WRITE_FILE","CREATE_DIRECTORY"],permissions:["OBSERVE","WRITE_WORKSPACE"] as SkillPermission[],actionIds:["workspace.read","workspace.write","workspace.mkdir","*"],idempotencySupport:true,retryPolicy:{maxAttempts:1,backoffMs:0,maxBackoffMs:0,retryable:false},
 async execute(ctx:AdapterExecutionContext,action:SkillAction):Promise<AdapterResult>{const root=ctx.workspaceRoot;if(!root)return{status:"REJECTED",message:"WORKSPACE_ROOT_REQUIRED",retryable:false};try{
  if(action.id==="workspace.read"){const rel=String(ctx.input.path??"");const abs=safeRelative(root,rel);const data=await fs.readFile(abs,"utf8");return{status:"EXECUTED",message:"Workspace file read.",output:{path:rel,content:data,sha256:createHash("sha256").update(data).digest("hex")},provenance:{adapter:"core.workspace.v1",path:rel}};}
  if(action.sideEffect==="FILE_WRITE"){const rel=String(ctx.input.path??"");assertNoSecret(rel);const abs=safeRelative(root,rel);const content=String(ctx.input.content??"");await fs.mkdir(path.dirname(abs),{recursive:true});try{await fs.writeFile(abs,content,{encoding:"utf8",flag:"wx"});}catch(e){if((e as NodeJS.ErrnoException).code!=="EEXIST")throw e;const existing=await fs.readFile(abs,"utf8");if(!ctx.idempotencyKey||existing!==content)throw e;}return{status:"EXECUTED",message:"Workspace file written.",output:{path:rel,sha256:createHash("sha256").update(content).digest("hex"),manifest:[{path:rel,sha256:createHash("sha256").update(content).digest("hex"),bytes:Buffer.byteLength(content)}]},provenance:{adapter:"core.workspace.v1",path:rel,idempotencyKey:ctx.idempotencyKey}};}
  if(action.id==="workspace.mkdir"){const rel=String(ctx.input.path??"");assertNoSecret(rel);await fs.mkdir(safeRelative(root,rel),{recursive:true});return{status:"EXECUTED",message:"Workspace directory created.",output:{path:rel},provenance:{adapter:"core.workspace.v1",path:rel}};}
  return{status:"REJECTED",message:"WORKSPACE_ACTION_UNSUPPORTED",retryable:false};
 }catch(e){return{status:"FAILED",message:e instanceof Error?e.message:"WORKSPACE_EXECUTION_FAILED",retryable:false};}}
};
export const sandboxAdapter={id:"core.sandbox.v1",version:"1.0.0",capabilities:["RUN_ALLOWLISTED_COMMAND"],permissions:["EXECUTE_SANDBOX"] as SkillPermission[],actionIds:["sandbox.run"],idempotencySupport:false,retryPolicy:{maxAttempts:2,backoffMs:250,maxBackoffMs:1000,retryable:true},
 async execute(ctx:AdapterExecutionContext,action:SkillAction):Promise<AdapterResult>{if(action.id!=="sandbox.run")return{status:"REJECTED",message:"SANDBOX_ACTION_UNSUPPORTED",retryable:false};const command=String(ctx.input.command??"").trim();const args=Array.isArray(ctx.input.args)?ctx.input.args.map(String):[];const allowed=(process.env.CORE_ENGINE_SANDBOX_ALLOWLIST??"").split(",").map(x=>x.trim()).filter(Boolean);if(!allowed.includes(command))return{status:"REJECTED",message:"SANDBOX_COMMAND_NOT_ALLOWLISTED",retryable:false};if(!ctx.workspaceRoot)return{status:"REJECTED",message:"SANDBOX_WORKSPACE_REQUIRED",retryable:false};const timeoutMs=Math.min(Math.max(Number(ctx.input.timeoutMs??10000),100),30000),outputLimit=Math.min(Math.max(Number(ctx.input.outputLimit??65536),1024),262144);const{spawn}=await import("node:child_process");return await new Promise<AdapterResult>(resolve=>{const child=spawn(command,args,{cwd:ctx.workspaceRoot,shell:false,windowsHide:true});let stdout="",stderr="",timed=false;const timer=setTimeout(()=>{timed=true;child.kill("SIGKILL");},timeoutMs);child.stdout.on("data",d=>{stdout=(stdout+d.toString()).slice(0,outputLimit)});child.stderr.on("data",d=>{stderr=(stderr+d.toString()).slice(0,outputLimit)});child.on("error",e=>{clearTimeout(timer);resolve({status:"FAILED",message:e.message,retryable:false})});child.on("close",(code,signal)=>{clearTimeout(timer);resolve({status:code===0&&!timed?"EXECUTED":"FAILED",message:timed?"SANDBOX_TIMEOUT":"Sandbox exited with code "+(code??"null"),output:{exitCode:code,signal,stdout,stderr,truncated:stdout.length>=outputLimit||stderr.length>=outputLimit},retryable:timed})});})}}
