import type {SkillPack,SkillAction} from "./contracts";
import {registerSkillPack,registerSkillAdapter} from "./registry";
import {workspaceAdapter,sandboxAdapter} from "./adapters";
const retry={maxAttempts:1,backoffMs:0,maxBackoffMs:0,retryable:false};
const ro=(id:string,name:string,description:string,adapterId:string):SkillAction=>({id,name,description,risk:"LOW",permissions:["OBSERVE"],sideEffect:"NONE",requiresApproval:false,requiresIdempotency:false,adapterId,input:{type:"object"},output:{type:"object"},retryPolicy:retry});
const write=(id:string,name:string,description:string):SkillAction=>({id,name,description,risk:"HIGH",permissions:["WRITE_WORKSPACE"],sideEffect:"FILE_WRITE",requiresApproval:true,requiresIdempotency:true,adapterId:"core.workspace.v1",input:{type:"object",required:["path","content"]},output:{type:"object"},retryPolicy:retry});
const packs:SkillPack[]=[
{id:"android-development",name:"Android App Builder",version:"2.0.0",description:"Android requirements, Kotlin/Compose implementation, build and tests.",categories:["android","mobile","kotlin","compose"],signals:["android","kotlin","compose","mobile"],actions:[ro("android.requirements.analyze","Analyze Android requirements","Analyze requirements and user flows.","core.android-build.v1"),write("android.project.scaffold","Scaffold Android project","Create an approved Android project structure."),write("android.feature.implement","Implement Android feature","Write approved Kotlin/Compose implementation."),ro("android.build","Build Android project","Run a bounded Android build.","core.android-build.v1"),ro("android.test","Test Android project","Run Android tests.","core.android-test.v1")]},
{id:"enterprise-proposals",name:"Enterprise Proposal Builder",version:"2.0.0",description:"Enterprise discovery, scope, pricing, ROI, risk and proposal artifacts.",categories:["proposal","enterprise","commercial"],signals:["proposal","roi","pricing","enterprise"],actions:[ro("proposal.discovery","Proposal discovery","Structure customer requirements.","core.web-search.v1"),ro("proposal.analyze","Analyze proposal","Analyze scope, evidence and risk.","core.web-search.v1"),write("proposal.compose","Compose proposal","Write an approved proposal artifact."),ro("proposal.pricing","Pricing scenarios","Model pricing scenarios without external side effects.","core.workspace.v1"),ro("proposal.validate","Validate proposal","Validate proposal completeness and evidence.","core.workspace.v1"),write("proposal.export","Export proposal","Write an approved proposal export.")]},
{id:"business-research",name:"Business Research and Evidence",version:"2.0.0",description:"Market research, provenance, confidence and evidence synthesis.",categories:["research","evidence","market"],signals:["research","evidence","sources","market","competition"],actions:[ro("research.collect","Collect research","Collect evidence through an approved research adapter.","core.web-search.v1"),ro("research.synthesize","Synthesize evidence","Separate facts, hypotheses, estimates and recommendations.","core.workspace.v1")]},
{id:"product-ux-accessibility",name:"Product UX and Accessibility",version:"2.0.0",description:"Journeys, flows, information architecture and accessibility.",categories:["ux","accessibility","product"],signals:["ux","accessibility","wcag","journey","flow"],actions:[ro("ux.journey.map","Map user journey","Map personas and journeys.","core.workspace.v1"),ro("ux.flow.specify","Specify product flow","Specify interaction and UI states.","core.workspace.v1"),ro("ux.accessibility.review","Review accessibility","Review WCAG, keyboard and navigation requirements.","core.security-scan.v1"),ro("ux.design.approve","Review design","Review design against defined acceptance criteria.","core.workspace.v1")]},
{id:"security-quality-assurance",name:"Security and Quality Assurance",version:"2.0.0",description:"Threat modeling, privacy, QA strategy and release gates.",categories:["security","qa","quality","release"],signals:["security","privacy","qa","quality","release","test"],actions:[ro("security.threat.model","Threat model","Identify assets, trust boundaries and threats.","core.security-scan.v1"),ro("security.privacy.review","Privacy review","Review data flows and privacy risks.","core.security-scan.v1"),ro("qa.strategy.create","Create QA strategy","Define test strategy and release evidence.","core.workspace.v1"),ro("security.release.gate","Security release gate","Evaluate release readiness and remediation evidence.","core.security-scan.v1")]}
];
export function registerBuiltInSkillPacks(){for(const a of [workspaceAdapter,sandboxAdapter])try{registerSkillAdapter(a)}catch(e){if(!(e instanceof Error)||!e.message.startsWith("SKILL_ADAPTER_ALREADY_REGISTERED"))throw e;}for(const p of packs)try{registerSkillPack(p)}catch(e){if(!(e instanceof Error)||!e.message.startsWith("SKILL_PACK_ALREADY_REGISTERED"))throw e;}}
