import {listSkillPacks,getSkillAdapter} from "./registry";
import type {SkillPlan,SkillPlanPhase,SkillPlanStep,SkillAcceptanceCriterion,SkillArtifactSpec} from "./contracts";
const terms:Record<string,string[]>={android:["android","kotlin","compose","mobile","aplikację android","aplikacja android","mobilną","mobilna"],ux:["ux","ui","accessibility","wcag","user flow","journey","interfejs","dostępność","nawigac"],security:["security","bezpieczeń","threat","privacy","qa","quality","release","test","audit","ryzyko"],proposal:["proposal","ofert","enterprise","roi","pricing","klient","zarząd","scope"],research:["research","badanie","rynek","konkurenc","evidence","źródła","sources"]};
const phaseFor=(id:string)=>id.startsWith("android.")?"build":id.startsWith("ux.")?"experience":id.startsWith("security.")||id.startsWith("qa.")?"assurance":id.startsWith("proposal.")?"proposal":"research";
const defaults=(id:string):{artifacts:SkillArtifactSpec[];criteria:SkillAcceptanceCriterion[]}=>{if(id.includes("research"))return{artifacts:[{id:"evidence-ledger",kind:"EVIDENCE",description:"Traceable evidence with source provenance.",required:true}],criteria:[{id:"evidence-provenance",description:"Claims remain traceable to evidence or explicitly marked as hypotheses.",verification:"DETERMINISTIC",blocking:true}]};if(id.includes("security"))return{artifacts:[{id:"security-report",kind:"REPORT",description:"Threat, privacy and release findings.",required:true}],criteria:[{id:"security-gate",description:"No unresolved blocking security finding is silently accepted.",verification:"ADAPTER",blocking:true}]};if(id.includes("ux"))return{artifacts:[{id:"ux-spec",kind:"DOCUMENT",description:"Journey, interaction and accessibility specification.",required:true}],criteria:[{id:"wcag-review",description:"Accessibility requirements are explicitly reviewed and recorded.",verification:"HUMAN",blocking:true}]};if(id.includes("proposal"))return{artifacts:[{id:"proposal",kind:"DOCUMENT",description:"Validated enterprise proposal artifact.",required:true}],criteria:[{id:"proposal-validation",description:"Proposal scope, assumptions, evidence and commercial model are validated.",verification:"DETERMINISTIC",blocking:true}]};return{artifacts:[{id:"workspace-manifest",kind:"FILE",description:"Manifest of generated project files.",required:true}],criteria:[{id:"build-integrity",description:"Generated project remains internally consistent and bounded to the approved workspace.",verification:"ADAPTER",blocking:true}]};};
export function planSkills(input:{objective:string;locale?:string;executionMode?:SkillPlan["executionMode"]}):SkillPlan{
 const objective=input.objective.trim(),q=objective.toLowerCase();const matched=new Set<string>();
 for(const [key,values] of Object.entries(terms))if(values.some(t=>q.includes(t)))matched.add(key);
 const selected=listSkillPacks().filter(p=>p.categories.some(c=>matched.has(c.toLowerCase())||[p.id,p.name,p.description,...p.signals].join(" ").toLowerCase().includes(c.toLowerCase())&&matched.size>0));
 const steps:SkillPlanStep[]=[];const missing=new Set<string>();const allArtifacts:SkillArtifactSpec[]=[];const allCriteria:SkillAcceptanceCriterion[]=[];
 for(const pack of selected)for(const action of pack.actions){const adapter=getSkillAdapter(action.adapterId);if(!adapter)missing.add(action.adapterId);const d=defaults(action.id);const artifacts=action.produces??d.artifacts;const criteria=action.acceptanceCriteria??d.criteria;const id=pack.id+":"+action.id;const depends=(action.dependsOn??[]).map(x=>x.includes(":")?x:pack.id+":"+x);steps.push({id,skillId:pack.id,actionId:action.id,adapterId:action.adapterId,risk:action.risk,permissions:action.permissions,sideEffect:action.sideEffect,requiresApproval:action.requiresApproval,requiresIdempotency:action.requiresIdempotency,retryPolicy:action.retryPolicy,status:adapter?"PLANNED":"BLOCKED",reason:adapter?undefined:"PLAN_ONLY_UNTIL_ADAPTERS_REGISTERED",dependsOn:depends,produces:artifacts,acceptanceCriteria:criteria});allArtifacts.push(...artifacts);allCriteria.push(...criteria);}
 const phases:SkillPlanPhase[]=[];for(const name of ["research","experience","build","proposal","assurance"]){const phaseSteps=steps.filter(s=>phaseFor(s.actionId)===name);if(phaseSteps.length)phases.push({id:name,name:name[0].toUpperCase()+name.slice(1),purpose:name==="assurance"?"Validate quality, security and release readiness":"Produce the evidence or artifacts required by downstream phases.",stepIds:phaseSteps.map(s=>s.id)});}
 return {runtime:"skill-runtime-v2",planVersion:"2.1",executionMode:input.executionMode??"PLAN_ONLY",objective,locale:input.locale??"en-US",phases,steps,selectedSkills:selected.map(x=>x.id),missingAdapters:[...missing],successCriteria:[...new Map(allCriteria.map(c=>[c.id,c])).values()],artifacts:[...new Map(allArtifacts.map(a=>[a.id,a])).values()]};
}