import { createLlmClient, LlmClientError } from "@/lib/cognition/llm-client";
import type { AdapterExecutionContext, AdapterResult, SkillAction, SkillPack, SkillPermission } from "./contracts";

type Card = { id:string; name:string; arcana:"MAJOR"|"MINOR"; keywords:string[]; upright:string; reversed:string };

const CARDS:Card[] = [
{id:"fool",name:"Głupiec",arcana:"MAJOR",keywords:["nowy początek","ryzyko","spontaniczność"],upright:"otwarcie się na nowy etap i zaufanie pierwszemu impulsowi",reversed:"lekkomyślność, brak planu lub ignorowanie sygnałów ostrzegawczych"},
{id:"magician",name:"Mag",arcana:"MAJOR",keywords:["sprawczość","komunikacja","intencja"],upright:"świadome działanie i użycie własnych zasobów",reversed:"manipulacja, niespójność słów i czynów lub niewykorzystany potencjał"},
{id:"high-priestess",name:"Kapłanka",arcana:"MAJOR",keywords:["intuicja","tajemnica","cisza"],upright:"potrzeba obserwacji, cierpliwości i słuchania intuicji",reversed:"tłumienie intuicji, ukrywanie informacji lub nadinterpretacja"},
{id:"empress",name:"Cesarzowa",arcana:"MAJOR",keywords:["bliskość","opieka","wzrost"],upright:"rozwój relacji przez troskę, obecność i emocjonalną dostępność",reversed:"nadopiekuńczość, zależność lub brak równowagi w dawaniu"},
{id:"emperor",name:"Cesarz",arcana:"MAJOR",keywords:["granice","stabilność","kontrola"],upright:"potrzeba jasnych zasad, odpowiedzialności i stabilności",reversed:"sztywność, kontrolowanie drugiej osoby lub walka o dominację"},
{id:"lovers",name:"Kochankowie",arcana:"MAJOR",keywords:["wybór","więź","wartości"],upright:"silna więź połączona z koniecznością świadomego wyboru",reversed:"rozbieżność wartości, ambiwalencja lub trudny wybór"},
{id:"chariot",name:"Rydwan",arcana:"MAJOR",keywords:["ruch","determinacja","kierunek"],upright:"ruch naprzód wymaga decyzji i kontroli własnego kierunku",reversed:"ciągnięcie relacji w przeciwne strony lub brak wspólnego celu"},
{id:"strength",name:"Siła",arcana:"MAJOR",keywords:["odwaga","cierpliwość","łagodność"],upright:"opanowanie emocji i spokojna konsekwencja",reversed:"niepewność, impulsywność lub tłumiona złość"},
{id:"hermit",name:"Pustelnik",arcana:"MAJOR",keywords:["dystans","refleksja","samotność"],upright:"czas na dystans i uporządkowanie własnych potrzeb",reversed:"izolacja, unikanie rozmowy lub utknięcie w analizowaniu"},
{id:"wheel",name:"Koło Fortuny",arcana:"MAJOR",keywords:["zmiana","cykl","zwrot"],upright:"sytuacja wchodzi w nowy etap i wymaga elastyczności",reversed:"powtarzanie starego schematu lub opór przed zmianą"},
{id:"justice",name:"Sprawiedliwość",arcana:"MAJOR",keywords:["prawda","konsekwencje","równowaga"],upright:"potrzeba szczerej oceny faktów i konsekwencji",reversed:"nierównowaga, zaprzeczanie faktom lub unikanie odpowiedzialności"},
{id:"hanged-man",name:"Wisielec",arcana:"MAJOR",keywords:["pauza","perspektywa","odpuszczenie"],upright:"brak ruchu służy zmianie perspektywy",reversed:"przedłużanie zawieszenia bez realnej zmiany"},
{id:"death",name:"Śmierć",arcana:"MAJOR",keywords:["koniec","transformacja","odcięcie"],upright:"stary układ wymaga zakończenia, aby zrobić miejsce nowemu",reversed:"trzymanie się sytuacji, która już się zmieniła"},
{id:"temperance",name:"Umiarkowanie",arcana:"MAJOR",keywords:["harmonia","tempo","równowaga"],upright:"relacja potrzebuje spokojnego tempa i wzajemnego dostrajania",reversed:"skrajności, niecierpliwość lub brak równowagi"},
{id:"devil",name:"Diabeł",arcana:"MAJOR",keywords:["przywiązanie","pożądanie","schemat"],upright:"silne przyciąganie może mieszać się z zależnością lub obsesyjnym schematem",reversed:"uświadomienie sobie zależności i próba odzyskania autonomii"},
{id:"tower",name:"Wieża",arcana:"MAJOR",keywords:["wstrząs","prawda","przełom"],upright:"nagłe ujawnienie prawdy lub przełom w dotychczasowym układzie",reversed:"unikanie nieuniknionej zmiany lub tłumienie napięcia"},
{id:"star",name:"Gwiazda",arcana:"MAJOR",keywords:["nadzieja","uzdrowienie","wiara"],upright:"odbudowa zaufania i spokojna nadzieja",reversed:"utrata wiary, idealizacja lub rozczarowanie"},
{id:"moon",name:"Księżyc",arcana:"MAJOR",keywords:["niepewność","lęk","iluzja"],upright:"emocje są silne, ale obraz sytuacji pozostaje niepełny",reversed:"stopniowe wychodzenie z iluzji i porządkowanie faktów"},
{id:"sun",name:"Słońce",arcana:"MAJOR",keywords:["jasność","radość","otwartość"],upright:"szczerość i otwartość sprzyjają poprawie sytuacji",reversed:"radość jest możliwa, ale przesłaniają ją wątpliwości lub ego"},
{id:"judgement",name:"Sąd Ostateczny",arcana:"MAJOR",keywords:["przebudzenie","decyzja","powrót"],upright:"powrót do tematu i decyzja po okresie refleksji",reversed:"unikanie decyzji lub wracanie do przeszłości bez wniosków"},
{id:"world",name:"Świat",arcana:"MAJOR",keywords:["domknięcie","pełnia","nowy etap"],upright:"domknięcie cyklu i gotowość na kolejny etap",reversed:"niedomknięta sprawa utrudnia rozpoczęcie kolejnego etapu"}
];

const LOVE_TERMS=["miłość","relac","związek","partner","partnerka","chłopak","dziewcz","był","była","ex","wróci","odezw","uczuc","randk","małżeń","mąż","żona"];
const CAREER_TERMS=["praca","szef","karier","firma","awans","zwoln","biznes"];
const MONEY_TERMS=["pieniądze","finanse","zarob","dług","kredyt","inwest"];
const normalize=(v:unknown)=>String(v??"").trim();
const hashSeed=(text:string)=>{let h=2166136261;for(const c of text)h=Math.imul(h^c.charCodeAt(0),16777619);return h>>>0};
const next=(s:number)=>{let x=s||1;x^=x<<13;x^=x>>>17;x^=x<<5;return x>>>0};
function classify(q:string){const l=q.toLowerCase();const love=LOVE_TERMS.some(x=>l.includes(x));const career=CAREER_TERMS.some(x=>l.includes(x));const money=MONEY_TERMS.some(x=>l.includes(x));return {domain:love?"LOVE":career?"CAREER":money?"MONEY":"LIFE",confidence:love||career||money?0.92:0.62,questionType:l.includes("czy")?"YES_NO":"OPEN"}}
function draw(question:string,count:number){let seed=hashSeed(question),pool=[...CARDS],out:unknown[]=[];for(let i=0;i<count&&pool.length;i++){seed=next(seed);const idx=seed%pool.length;seed=next(seed);const reversed=(seed%100)<28;const card=pool.splice(idx,1)[0];out.push({position:i+1,cardId:card.id,name:card.name,orientation:reversed?"REVERSED":"UPRIGHT",keywords:card.keywords,meaning:reversed?card.reversed:card.upright});}return out}
function fallbackReading(q:string,cards:unknown[],domain:string){const names=(cards as Array<{name:string;orientation:string}>).map(c=>c.name+(c.orientation==="REVERSED"?" odwrócona":""));return {headline:domain==="LOVE"?"Odczyt relacyjny":"Twój odczyt",summary:"Ten odczyt jest symboliczną interpretacją kart wokół Twojego pytania. Nie jest pewną prognozą przyszłości.",cards,interpretation:"Układ wskazuje na potrzebę oddzielenia faktów od oczekiwań. Pierwsza karta opisuje główną energię sytuacji, druga pokazuje napięcie lub przeszkodę, a trzecia wskazuje kierunek refleksji. Nie traktuj pojedynczej karty jako dowodu intencji drugiej osoby.",synthesis:"Karty w tym układzie: "+names.join(", ")+". Najbardziej użyteczne pytanie brzmi: jaki następny krok jest zgodny z Twoimi granicami i faktami, które znasz?",reflectionPrompt:"Co w tej sytuacji wiesz na pewno, a co jest Twoją interpretacją?",disclaimer:"Odczyt ma charakter rozrywkowy i refleksyjny. Nie zastępuje profesjonalnej porady ani nie przewiduje pewnych zdarzeń."}}
async function llm(question:string,cards:unknown[],domain:string,ctx:AdapterExecutionContext){const tenantId=normalize(ctx.tenantId)||"wrozbita-public";const missionId=ctx.missionId;const client=createLlmClient({maxAttempts:2,timeoutMs:20000});const prompt={role:"user" as const,content:"Jesteś Wróżbitą AI. Interpretujesz tarot jako narzędzie symbolicznej refleksji i rozrywki, nie jako pewną przepowiednię. Nie twierdź, że znasz przyszłość, myśli lub intencje innej osoby. Odpowiadaj po polsku. Pytanie: "+question+"\nDomena: "+domain+"\nKarty: "+JSON.stringify(cards)+"\nZwróć JSON: headline, summary, interpretation, synthesis, reflectionPrompt, disclaimer."};try{const r=await client.complete({messages:[{role:"system",content:"Pisz konkretnie, empatycznie i bez fatalizmu. Unikaj porad medycznych, prawnych i finansowych. Nie wzmacniaj zależności od AI."},prompt],temperature:0.7,maxTokens:900,audit:{tenantId,missionId,operation:"wrozbita_reading",promptName:"WROZBITA_READING",promptVersion:"1.0.0",promptHash:"wrozbita-v1"}});const parsed=JSON.parse(r.content) as Record<string,unknown>;return{...parsed,cards,source:"LLM",model:r.model}}catch(e){if(e instanceof LlmClientError&&e.kind==="NOT_CONFIGURED")return{...fallbackReading(question,cards,domain),source:"DETERMINISTIC_FALLBACK"};throw e}}
export const wrozbitaAdapter={id:"core.wrozbita.v1",version:"1.0.0",capabilities:["QUESTION_CLASSIFICATION","TAROT_SPREAD_SELECTION","DETERMINISTIC_CARD_DRAW","AI_READING_SYNTHESIS","FOLLOWUP_PROMPT"],permissions:["OBSERVE"] as SkillPermission[],actionIds:["wrozbita.question.classify","wrozbita.spread.select","wrozbita.cards.draw","wrozbita.reading.synthesize","wrozbita.followup.generate"],idempotencySupport:false,retryPolicy:{maxAttempts:2,backoffMs:200,maxBackoffMs:1000,retryable:true},observationalOnly:true,
async execute(ctx:AdapterExecutionContext,action:SkillAction):Promise<AdapterResult>{const q=normalize(ctx.input.question);if(!q)return{status:"REJECTED",message:"QUESTION_REQUIRED"};if(action.id==="wrozbita.question.classify")return{status:"EXECUTED",message:"Question classified.",output:classify(q),provenance:{adapter:"core.wrozbita.v1"}};if(action.id==="wrozbita.spread.select")return{status:"EXECUTED",message:"Spread selected.",output:{spreadId:"love-3" ,positions:["sytuacja","napięcie","kierunek refleksji"],count:3},provenance:{adapter:"core.wrozbita.v1"}};if(action.id==="wrozbita.cards.draw"){const count=Math.min(5,Math.max(1,Number(ctx.input.count??3)));return{status:"EXECUTED",message:"Cards drawn deterministically from the configured deck.",output:{cards:draw(q,count)},provenance:{adapter:"core.wrozbita.v1",drawMethod:"seeded-fnv-xorshift",deckSize:CARDS.length}};};if(action.id==="wrozbita.reading.synthesize"){const cards=Array.isArray(ctx.input.cards)?ctx.input.cards:[];const domain=normalize(ctx.input.domain)||"LIFE";const result=await llm(q,cards,domain,ctx);return{status:"EXECUTED",message:"Reading synthesized.",output:result,provenance:{adapter:"core.wrozbita.v1",observationalOnly:true}}};if(action.id==="wrozbita.followup.generate")return{status:"EXECUTED",message:"Follow-up generated.",output:{question:"Co chcesz sprawdzić jako następne: emocje, kontakt, przeszkodę czy kierunek relacji?",suggested:["emocje","kontakt","przeszkoda","kierunek"]},provenance:{adapter:"core.wrozbita.v1"}};return{status:"REJECTED",message:"WROZBITA_ACTION_UNSUPPORTED"}}};