export type LlmMessage={role:"system"|"user"|"assistant";content:string};
export type LlmAuditContext={tenantId:string;missionId?:string;operation:string;promptName:string;promptVersion:string;promptHash:string};
export type LlmRequest={messages:LlmMessage[];temperature?:number;maxTokens?:number;audit:LlmAuditContext};
export type LlmResponse={content:string;model:string;latencyMs:number;promptTokens?:number;completionTokens?:number;totalTokens?:number};
export type LlmErrorKind="NOT_CONFIGURED"|"AUTH"|"RATE_LIMIT"|"TIMEOUT"|"NETWORK"|"BAD_REQUEST"|"SERVER"|"INVALID_RESPONSE"|"AUDIT_FAILED"|"UNKNOWN";
export class LlmClientError extends Error{readonly kind:LlmErrorKind;readonly retryable:boolean;readonly status?:number;readonly providerCode?:string;constructor(i:{kind:LlmErrorKind;message:string;retryable:boolean;status?:number;providerCode?:string}){super(i.message);this.name="LlmClientError";this.kind=i.kind;this.retryable=i.retryable;this.status=i.status;this.providerCode=i.providerCode}}
type AuditWriter=(i:{audit:LlmAuditContext;model:string;requestMessages:LlmMessage[];responseContent:string|null;latencyMs:number;promptTokens?:number;completionTokens?:number;totalTokens?:number;success:boolean;errorKind?:LlmErrorKind})=>Promise<void>;
type Options={fetchImpl?:typeof fetch;sleep?:(ms:number)=>Promise<void>;auditWriter?:AuditWriter;maxAttempts?:number;timeoutMs?:number};
const endpoint=(base:string)=>/\/chat\/completions$/i.test(base)?base:base.replace(/\/$/,"")+(base.endsWith("/v1")?"/chat/completions":"/v1/chat/completions");
function config(){const base=process.env.CORE_ENGINE_LLM_BASE_URL?.trim(),key=process.env.CORE_ENGINE_LLM_API_KEY?.trim(),model=process.env.CORE_ENGINE_LLM_MODEL?.trim();if(!base||!key||!model)throw new LlmClientError({kind:"NOT_CONFIGURED",message:"LLM provider is not configured.",retryable:false});return{base,key,model}}
function classify(status:number){if(status===401||status===403)return["AUTH",false] as const;if(status===429)return["RATE_LIMIT",true] as const;if([400,404,422].includes(status))return["BAD_REQUEST",false] as const;if(status>=500)return["SERVER",true] as const;return["UNKNOWN",false] as const}
async function durableAudit(i:Parameters<AuditWriter>[0]){const url=process.env.SUPABASE_URL?.trim(),key=(process.env.SUPABASE_SECRET_KEY||process.env.SUPABASE_SERVICE_ROLE_KEY)?.trim();if(!url||!key)throw new LlmClientError({kind:"AUDIT_FAILED",message:"Durable LLM audit configuration is missing.",retryable:false});const r=await fetch(url.replace(/\/$/,"")+"/rest/v1/ce_cognition_audit_events",{method:"POST",cache:"no-store",headers:{apikey:key,Authorization:"Bearer "+key,"Content-Type":"application/json",Prefer:"return=minimal"},body:JSON.stringify({tenant_id:i.audit.tenantId,mission_id:i.audit.missionId??null,operation:i.audit.operation,prompt_name:i.audit.promptName,prompt_version:i.audit.promptVersion,prompt_hash:i.audit.promptHash,model:i.model,request_messages:i.requestMessages,response_content:i.responseContent,latency_ms:i.latencyMs,prompt_tokens:i.promptTokens??null,completion_tokens:i.completionTokens??null,total_tokens:i.totalTokens??null,success:i.success,error_kind:i.errorKind??null})});if(!r.ok)throw new LlmClientError({kind:"AUDIT_FAILED",message:"Durable LLM audit write failed.",retryable:false,status:r.status})}
export interface LlmClient{complete(request:LlmRequest):Promise<LlmResponse>}
export function createLlmClient(o:Options={}):LlmClient{const fetchImpl=o.fetchImpl??fetch,sleep=o.sleep??(ms=>new Promise<void>(r=>setTimeout(r,ms))),audit=o.auditWriter??durableAudit,maxAttempts=Math.max(1,Math.min(o.maxAttempts??3,5)),timeoutMs=Math.max(1000,o.timeoutMs??30000);return{async complete(request){const c=config();if(!request.messages.length)throw new LlmClientError({kind:"BAD_REQUEST",message:"At least one LLM message is required.",retryable:false});const started=Date.now();let last:LlmClientError|undefined;for(let attempt=1;attempt<=maxAttempts;attempt++){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),timeoutMs);try{const r=await fetchImpl(endpoint(c.base),{method:"POST",cache:"no-store",signal:controller.signal,headers:{Authorization:"Bearer "+c.key,"Content-Type":"application/json"},body:JSON.stringify({model:c.model,messages:request.messages,temperature:request.temperature??0,...(request.maxTokens?{max_tokens:request.maxTokens}:{})})});if(!r.ok){const [kind,retryable]=classify(r.status);throw new LlmClientError({kind,message:"LLM provider request failed with HTTP "+r.status+".",retryable,status:r.status})}const p=await r.json() as {model?:string;choices?:Array<{message?:{content?:unknown}}>;usage?:{prompt_tokens?:number;completion_tokens?:number;total_tokens?:number}};const content=p.choices?.[0]?.message?.content;if(typeof content!=="string")throw new LlmClientError({kind:"INVALID_RESPONSE",message:"LLM provider returned no textual assistant content.",retryable:false});const result={content,model:typeof p.model==="string"?p.model:c.model,latencyMs:Date.now()-started,promptTokens:p.usage?.prompt_tokens,completionTokens:p.usage?.completion_tokens,totalTokens:p.usage?.total_tokens};await audit({audit:request.audit,model:result.model,requestMessages:request.messages,responseContent:result.content,latencyMs:result.latencyMs,promptTokens:result.promptTokens,completionTokens:result.completionTokens,totalTokens:result.totalTokens,success:true});return result}catch(e){const n=e instanceof LlmClientError?e:e instanceof Error&&e.name==="AbortError"?new LlmClientError({kind:"TIMEOUT",message:"LLM provider request timed out.",retryable:true}):new LlmClientError({kind:"NETWORK",message:"LLM provider network request failed.",retryable:true});last=n;if(!n.retryable||attempt===maxAttempts){try{await audit({audit:request.audit,model:c.model,requestMessages:request.messages,responseContent:null,latencyMs:Date.now()-started,success:false,errorKind:n.kind})}catch{throw new LlmClientError({kind:"AUDIT_FAILED",message:"LLM failure audit could not be persisted.",retryable:false})}throw n}await sleep(attempt===1?250:500)}finally{clearTimeout(timer)}}throw last??new LlmClientError({kind:"UNKNOWN",message:"LLM request failed.",retryable:false})}}}