import { authorizeTenant } from "@/lib/http";
import { NextResponse } from "next/server";
import { guardMutation } from "@/lib/http";
import { resolveTenant } from "@/lib/commercial-runtime";
import { createPolicyAwareRecoveryDecisionEngine } from "@/lib/m24-28-policy-aware-decision-engine";
import { hashRecoveryDecision, verifyPolicyEscalation } from "@/lib/recovery-approval-gate";
import { createSupabaseRecoveryEscalationEvidencePersistence } from "@/lib/m24-32-escalation-evidence-persistence";
import { verifyPersistedEscalationEvidence } from "@/lib/m24-33-escalation-evidence-integrity";
function validBody(value:unknown):value is {recoveryKey:string;idempotencyKey:string}{if(!value||typeof value!=="object")return false;const b=value as Record<string,unknown>;return typeof b.recoveryKey==="string"&&b.recoveryKey.length>0&&b.recoveryKey.length<=200&&typeof b.idempotencyKey==="string"&&b.idempotencyKey.length>0&&b.idempotencyKey.length<=200}
export async function POST(request:Request){try{const guard=guardMutation(request,"recovery-escalation-evidence");if(guard)return guard;const tenant=resolveTenant(request);const body=await request.json();if(!validBody(body))return NextResponse.json({ok:false,error:"RECOVERY_ESCALATION_EVIDENCE_INPUT_INVALID"},{status:400});const decision=await createPolicyAwareRecoveryDecisionEngine().decide(tenant.tenantId,body.recoveryKey);if(!decision)return NextResponse.json({ok:false,error:"RECOVERY_NOT_FOUND"},{status:404});const policyWeight=decision.selectedPolicy?{netWeight:decision.selectedPolicy.netWeight,confidenceBps:decision.selectedPolicy.confidenceBps,sampleCount:decision.selectedPolicy.sampleCount,policyVersion:decision.selectedPolicy.policyVersion}:null;const verification=verifyPolicyEscalation(policyWeight,decision);const persisted=await createSupabaseRecoveryEscalationEvidencePersistence().commit({tenantId:tenant.tenantId,recoveryKey:body.recoveryKey,idempotencyKey:body.idempotencyKey,decisionHash:hashRecoveryDecision(decision),policyWeight,verification});const integrity=verifyPersistedEscalationEvidence(persisted,hashRecoveryDecision(decision));return NextResponse.json({ok:true,flow:"POLICY ESCALATION → VERIFICATION → EVIDENCE → PERSISTENCE → REPLAY INTEGRITY",decision,verification,persisted,integrity},{status:200})}catch(error){const message=error instanceof Error?error.message:"RECOVERY_ESCALATION_EVIDENCE_FAILED";return NextResponse.json({ok:false,error:message},{status:message.includes("CONFLICT")?409:400})}}
export async function GET(request:Request){
  const auth = await authorizeTenant(request); if (!auth.ok) return auth.response;try{const tenant=resolveTenant(request);const url=new URL(request.url);const recoveryKey=url.searchParams.get("recoveryKey");const evidenceId=url.searchParams.get("evidenceId");if(!recoveryKey)return NextResponse.json({ok:false,error:"RECOVERY_ESCALATION_EVIDENCE_INPUT_INVALID"},{status:400});const records=await createSupabaseRecoveryEscalationEvidencePersistence().read(tenant.tenantId,recoveryKey);const selected=evidenceId?records.filter(r=>r.evidenceId===evidenceId):records;const decision=await createPolicyAwareRecoveryDecisionEngine().decide(tenant.tenantId,recoveryKey);const expectedHash=decision?hashRecoveryDecision(decision):undefined;const integrity=selected.map(r=>verifyPersistedEscalationEvidence(r,expectedHash));const allValid=integrity.length>0&&integrity.every(r=>r.integrity==="VALID");return NextResponse.json({ok:true,tenantId:tenant.tenantId,recoveryKey,records,integrity,integrityStatus:allValid?"VALID":"FAILED"},{status:allValid?200:409})}catch(error){const message=error instanceof Error?error.message:"RECOVERY_ESCALATION_EVIDENCE_READ_FAILED";return NextResponse.json({ok:false,error:message},{status:400})}}