import{NextResponse}from"next/server";import{guardMutation}from"@/lib/http";import{rateLimit}from"@/lib/rate-limit";import{resolveSaaSContext}from"@/lib/saas-runtime";import{buildWorldState,resolveWorldContradiction,upsertWorldClaim}from"@/lib/world-model";
import{assessClaimConfidence,getClaimProvenance}from "@/lib/provenance-intelligence";
function tenant(r:Awaited<ReturnType<typeof resolveSaaSContext>>){return r.identity?.tenantId??r.legacyTenant?.tenantId;}
export async function GET(request:Request){try{const r=await resolveSaaSContext(request);const tenantId=tenant(r);if(!tenantId)return NextResponse.json({ok:false,error:"AUTH_REQUIRED"},{status:401});const u=new URL(request.url);const worldState=await buildWorldState({tenantId,domain:u.searchParams.get("domain")??"business",persistSnapshot:u.searchParams.get("snapshot")==="true"});return NextResponse.json({ok:true,worldState});}catch(error){return NextResponse.json({ok:false,error:error instanceof Error?error.message:"WORLD_MODEL_FAILED"},{status:400});}}
export async function POST(request:Request){const guard=guardMutation(request,"world-model");if(guard)return guard;const rl=rateLimit("world-model:"+((request.headers.get("x-forwarded-for")||"unknown").split(",")[0]));if(!rl.allowed)return NextResponse.json({ok:false,error:"RATE_LIMITED"},{status:429});try{const r=await resolveSaaSContext(request);const tenantId=tenant(r);if(!tenantId)return NextResponse.json({ok:false,error:"AUTH_REQUIRED"},{status:401});const b=await request.json() as Record<string,unknown>;
if(b.operation==="claim"){if(typeof b.subjectKey!=="string"||typeof b.predicate!=="string")return NextResponse.json({ok:false,error:"SUBJECT_AND_PREDICATE_REQUIRED"},{status:400});const result=await upsertWorldClaim({tenantId,subjectKey:b.subjectKey,predicate:b.predicate,objectValue:b.objectValue,domain:typeof b.domain==="string"?b.domain:"business",confidence:typeof b.confidence==="number"?b.confidence:undefined,source:typeof b.source==="string"?b.source:"CORE_ENGINE",sourceRef:typeof b.sourceRef==="string"?b.sourceRef:undefined,observedAt:typeof b.observedAt==="string"?b.observedAt:undefined,validUntil:typeof b.validUntil==="string"?b.validUntil:undefined,valueType:typeof b.valueType==="string"?b.valueType:undefined,metadata:b.metadata&&typeof b.metadata==="object"&&!Array.isArray(b.metadata)?b.metadata as Record<string,unknown>:undefined});return NextResponse.json({ok:true,result});}
if(b.operation==="assess_claim"){if(typeof b.claimId!=="string"||typeof b.sourceType!=="string"||typeof b.source!=="string")return NextResponse.json({ok:false,error:"CLAIM_SOURCE_REQUIRED"},{status:400});const result=await assessClaimConfidence({tenantId,claimId:b.claimId,sourceType:b.sourceType,source:b.source,sourceRef:typeof b.sourceRef==="string"?b.sourceRef:undefined,sourceUri:typeof b.sourceUri==="string"?b.sourceUri:undefined,sourceHash:typeof b.sourceHash==="string"?b.sourceHash:undefined,observedAt:typeof b.observedAt==="string"?b.observedAt:undefined,freshnessAt:typeof b.freshnessAt==="string"?b.freshnessAt:undefined,authority:typeof b.authority==="number"?b.authority:undefined,reliability:typeof b.reliability==="number"?b.reliability:undefined,independence:typeof b.independence==="number"?b.independence:undefined,completeness:typeof b.completeness==="number"?b.completeness:undefined,directness:typeof b.directness==="number"?b.directness:undefined,reason:typeof b.reason==="string"?b.reason:undefined});return NextResponse.json({ok:true,result});}
if(b.operation==="provenance"){if(typeof b.claimId!=="string")return NextResponse.json({ok:false,error:"CLAIM_ID_REQUIRED"},{status:400});const result=await getClaimProvenance({tenantId,claimId:b.claimId});return NextResponse.json({ok:true,provenance:result});}
if(b.operation==="resolve_contradiction"){if(typeof b.contradictionId!=="string"||typeof b.resolution!=="string")return NextResponse.json({ok:false,error:"CONTRADICTION_ID_AND_RESOLUTION_REQUIRED"},{status:400});const result=await resolveWorldContradiction({tenantId,contradictionId:b.contradictionId,winningClaimId:typeof b.winningClaimId==="string"?b.winningClaimId:undefined,resolution:b.resolution});return NextResponse.json({ok:true,result});}
if(b.operation==="refresh"){const worldState=await buildWorldState({tenantId,domain:typeof b.domain==="string"?b.domain:"business",persistSnapshot:true});return NextResponse.json({ok:true,worldState});}return NextResponse.json({ok:false,error:"UNKNOWN_WORLD_MODEL_OPERATION"},{status:400});}catch(error){return NextResponse.json({ok:false,error:error instanceof Error?error.message:"WORLD_MODEL_OPERATION_FAILED"},{status:400});}}